var step = '<font class="fontSize">'
           + '<p>Test Purpose: </p>'
           + '<p>Verifies the media capture APIs could access from localhost.</p>'
           + '<p>Test Pre-condition: </p>'
            +'<p>Start Tinyweb server and install docroot.zip.</p>'
           + '<p>Test Steps: </p>'
             + '<ol>'
               + '<li>Click the "Allow" if a camera requesting prompt pops up.</li>'
             + '</ol>'
           + '<p>Expected Result: </p>'
           + '<p>Camera launched successfully.</p>'
         + '</font>'
