var step = '<font class="fontSize">'
            +'<p>Purpose:</p>'
            +'<p>Validate open the URL in app windows itself when the xwalk_hosts field with match patterns * in manifest</p>'
            +'<p>Expected Result:</p>'
            +'<ol>'
            +'<li>The webapp install successfully and launch successfully.</li>'
            +'<li>Open "URL(http)" in the app windows itself.</li>'
            +'<li>Open "URL(https)" in the app windows itself.</li>'
            +'</ol>'
          +'</font>';
