var step = '<font style="font-size:85%">'
              + '<p>Test Purpose: </p>'
              + '<p>Verifies the ringtone is successfully changed.</p>'
              + '<p>Test Step: </p>'
              + '<p>'
                + '<ol>'
                  + '<li>'
                    + 'Click "Set" button.'
                  + '</li>'
                  + '<li>'
                    + 'Click "get path" button.'
                  + '</li>'
                  + '<li>'
                    + 'Click "play" button.'
                  + '</li>'
                + '</ol>'
              + '</p>'
              + '<p>Expected Result: </p>'
              + '<p>Test passes if alert "Change of INCOMING_CALL ringtone" after step 1, and then alert "Sound(Get) path" value after step 2, and then the sound can play afer step 3.</p>'
            + '</font>'
