var step = '<font class="fontSize">'
            +'<p>Pre-condition:</p>'
            +'<ul>'
            +'<li>The plugin dialogs and vibration have been installed</li>'
            +'</ul>'
            +'<p>Purpose:</p>'
            +'<p>Verify the functions of notification can work well</p>'
            +'<p>Test Steps:</p>'
            +'<ol>'
            +'<li>Click "Play Beep"</li>'
            +'<li>Click "Vibrate"</li>'
            +'<li>Click "Confirm Dialog"</li>'
            +'<li>Click "Prompt Dialog"</li>'
            +'</ol>'
            +'<p>Expected Results:</p>'
            +'<ol>'
            +'<li>Beep three times</li>'
            +'<li>Vibrate 3 seconds</li>'
            +'<li>Pop-up confirm box</li>'
            +'<li>Pop-up prompt box</li>'
            +'</ol>'
          +'</font>';
