var step = '<font class="fontSize">'
            +'<p>Purpose:</p>'
            +'<p>Verifies that Hard Key of device can work properly</p>'
            +'<p>Test Steps:</p>'
            +'<ol>'
            +'<li>Click "Launch Test Page" button</li>'
            +'<li>Click "Play" button to play the video</li>'
            +'<li>The volume could be adjusted with the "volumn" button</li>'
            +'<li>Click fullscreen button</li>'
            +'<li>Click fullscreen button</li>'
            +'<li>Press Back key</li>'
            +'<li>Press Home key</li>'
            +'</ol>'
            +'<p>Expected Result:</p>'
            +'<ol>'
            +'<li>Test page could be launched successfully</li>'
            +'<li>The video played normally and could sound some voice</li>'
            +'<li>The volume could be turned up/down when pressing "volume+/-" button</li>'
            +'<li>The video could be switched to fullscreen and played normally</li>'
            +'<li>Exit fullscreen</li>'
            +'<li>Back to the previous page</li>'
            +'<li>Back to main window successfully</li>'
            +'</ol>'
          +'</font>';
