var step = '<font class="fontSize">'
           + '<p>Test Purpose: </p>'
           + '<p>Verifies push message then get web notification.</p>'
           + '<p>Test Step: </p>'
           + '<p>'
             + '<ol>'
               + '<li>'
                 + 'Click the "Enable Push Messages" button.'
               + '</li>'
               + '<li>'
                 + 'Run the curl command from a terminal.'
               + '</li>'
             + '</ol>'
           + '</p>'
           + '<p>Expected Result: </p>'
           + '<p>Test passes if create an curl command in box area after step 1, then show a notification after step 2.</p>'
         + '</font>'
