var step = '<font class="fontSize">'
           + '<p>Test Purpose: </p>'
           + '<p>Verifies SpeechRecognition realated interface work well.</p>'
           + '<p>Pre-condition: </p>'
           + '<p>Requires the network connection that could connect to speech recognition service.</p>'
           + '<p>Requires the working mic on the test device.</p>'
           + '<p>Test steps: </p>'
           + '<p>Click on the microphone icon and begin speaking whatever you want</p>'
           + '<p>Expected Result: </p>'
           + '<p>Test passes if words show in the textarea under the</p>'
           + '<p>correct liftcycle of SpeechRecognition.</p>'
         + '</font>'
