var step = '<font class="fontSize">'
            +'<p>Test Steps:</p>'
            +'<ol>'
            +'<li>Set the locale language to French, then click the input</li>'
            +'<li>Click the third button</li>'
            +'</ol>'
            +'<p>Expected Result:</p>'
            +'<ol>'
            +'<li>Display a calendar window</li>'
            +'<li>Globalization: Display the current date in FR format DD/MM/YYYY, like "21/01/2015". The MM/DD/YYYY like 01/21/2015 is not expected.</li>'
            +'</ol>'
          +'</font>';
