var step = '<font class="fontSize">'
            +'<p>Test Purpose: </p>'
            +'<p>Verifies the Applicationinformation and ApplicationContext interface are valid.</p>'
            +'<p>Verifies ApplicationManager.launch/kill/getCurrentApplication/getAppContext/getAppsContext methods are supported and valid.</p>'
            +'<p>Verifies ApplicationMnager.addAppinfoEventListener and install/uninstall/update events are supported and valid.</p>'
            +'<p>Test Steps: </p>'
              +'<ol>'
                +"<li>Run the application or click the 'CurrentApp' button, check if current application information can be shown</li>"
                +'<li>Click \'AllApp\' button, check if the application list can be shown</li>'
                +'<li>Click the \'AppInfo\' link, check if the application information which you select can be shown</li>'
                +'<li>Click the \'Run App\' link, check if the application which you select can be run and success infromation can be shown</li>'
                +'<li>Click the \'AllContext\' button, check if contextId and appId of running applications can be shown</li>'
                +'<li>Click the \'Kill App\' link, check if specified applicaion can be closed</li>'
                +'<li>Click the \'CurrentContext\' button, check if contextId and appId of current application can be shown</li>'
              +'</ol>'
            +'<p>Expected Result: </p>'
            +'<p>Test passes if application information, application context and event notification can be got, kill and launch application normally.</p>'
          +'</font>';
