var step = '<font style="font-size:85%">'
           + '<p>Check if Package is successfully installed, updated and uninstalled</p><br>'
           + '<p>1. Install TestPackage1</p>'
           + '<p>2. Launch TestPackage1</p>'
           + '<p>3. Check if TestPackage is launched successfully</p>'
           + '<p>4. Automatically write the text("Package_Test") and click the OK button</p>'
           + '<p>5. Check the PASS text</p>'
           + '<p>6. Update TestPackage2</p>'
           + '<p>7. Launch TestPackage2</p>'
           + '<p>8. Check if TestPackage is updated and launched successfully</p>'
           + '<p>9. Automatically read the text("Package_Test") and click the OK button</p>'
           + '<p>10. Check the PASS text</p>'
           + '<p>11. Uninstall TestPackage</p>'
           + '<p>12. Launch TestPackage and check it fails</p>'
         + '</font>'
