var step = '<font class="fontSize">'
            +'<p>Purpose:</p>'
            +'<p>Verifies enables user to run pkgcmd with option to perform installation/uninstallation task</p>'
            +'<p>Expected Result:</p>'
            +'<ol>'
            +'<li>package can be installed successfully</li>'
            +'<li>package can be uninstalled successfully</li>'
            +'<li>type:rpm, xpk, wgt apps should displayed successfully</li>'
            +'<li>the $id information should be displayed successfully</li>'
            +'</ol>'
          +'</font>';
