var step = '<font style="font-size:85%">'
            +'<p>Test Purpose: </p>'
            +'<p>Check if operate datas of a table owned by an SQL-type data control provider successfully</p><br>'
            +'<p>Test Steps: </p>'
            +'<ol>'
              +'<li>Input the new_value and new_value_desc, click the \'add\'</li>'
              +'<li>Input the old_value and new_value_desc, click the \'update\'</li>'
              +'<li>Input the value, click the \'remove\'</li>'
            +'</ol>'
            +'<p>Expected Result: </p>'
            +'<p>Test passes if insert new row to the table, update value_desc of the table and delete row from the table successfully</p>'
          +'</font>';
