var step = '<font style="font-size:85%">'
           + '<p>Test Purpose: </p>'
           + '<p>Verifies the device supports tizen notification interface.</p>'
           + '<p>Test Step: </p>'
           + '<p>'
             + '<ol>'
               + '<li>'
                 + 'Click the "Show Notification" button.'
               + '</li>'
               + '<li>'
                 + 'Click the "Update Notification" button.'
               + '</li>'
               + '<li>'
                 + 'Click the "Send" button.'
               + '</li>'
               + '<li>'
                 + 'Click the "Remove All" button.'
               + '</li>'
             + '</ol>'
           + '</p>'
           + '<p>Expected Result: </p>'
           + '<p>Test passes if show a notification after step 1, and then the content of notification change after step 2, and then notifications messages show a lists afer step 3, and then notificaitons can be removed after step 4.</p>'
         + '</font>'
