var step = '<p>Purpose:</p>'
            +'<p>Verify that a separate 64-bit Crosswalk APK support in Google Play store.</p>'
            +'<p>Expected Results:</p>'
            +'<ol>'
            +'<li>The embedded app is started, and pop up get crosswalk dialog.</li>'
            +'<li>Crosswalk runtime is installed via Google Play store or other PRC store.</li>'
            +'<li>The embedded app is launched successfully.</li>'
            +'<li>The Crosswalk runtime name matched in table can be found by command line.</li>'
            +'<li>The shared app is started, and pop up get crosswalk dialog.</li>'
            +'<li>Crosswalk runtime is installed via Google Play store or other PRC store.</li>'
            +'<li>The shared app is launched successfully.</li>'
            +'<li>The Crosswalk runtime name matched in table can be found by command line.</li>'
            +'<li>The Crosswalk runtime is uninstalled successfully.</li>'
            +'</ol>';
