var step = '<font style="font-size:85%">'
           + '<p>Check if the screen status is successfully changed</p>'
           + '<p>(Note: Response time varies depends on the system setting)</p><br>'
           + '<p>* Setting -> Display -> Backlight time : 15 Seconds<p>'
           + '<p>1. Click Request SCREEN_DIM(After 15 second) : Check if the screen is dim. But Screen does not turn off</p>'
           + '<p>2. Click Request SCREEN_NORMAL(After 15 second) : Check if the screen does not dim and turn off</p>'
           + '<p>3. Click Release SCREEN(After 15 second) : Check the screen resource release(Screen is dim and turn off)</p>'
           + '<p>4. Click Turn SCREEN_OFF and check the screen is off immediately</p>'
        + '</font>'
