var step = '<font style="font-size:85%">'
            +'<p>Check if an application is launched on time</p><br>'
            +'<p>1. Install AlarmTest</p>'
            +'<p>2. Set absolute time</p>'
            +'<p>3. Set an interval</p>'
            +'<p>4. Save an absolute button</p>'
            +'<p>5. Watch AlarmTest is launched on time</p>'
            +'<p>6. Watch AlarmTest is launched after the interval</p>'
            +'<p>7. Remove the alarm</p>'
          +'</font>';
