var step = '<font class="fontSize">'
           + '<p>Test Purpose: </p>'
           + '<p>Verifies TCPSocket and TCPServerSocket can send and receive message.</p>'
           + '<p>Test Steps: </p>'
             + '<ol>'
               + '<li>Click the "Connect"</li>'
               + '<li>When TCPServersocket is connected successfully, input the message, and click the "Send"</li>'
               + '<li>Click the "Disconnect"</li>'
             + '</ol>'
           + '<p>Expected Result: </p>'
           + '<p>Test passes if TCPSocket can connect to TCPServerSocket, and TCPServerSocket send back whatever TCPSocket send to it.</p>'
         + '</font>'
