var step = '<font class="fontSize">'
            +'<p>Test Purpose: </p>'
            +'<p>Verifies the device supports drag and drop functions.</p>'
            +'<p>Test Step: </p>'
            +'<ol>'
              +'<li>Click the "Launch" button to launch the test html.</li>'
            +'</ol>'
            +'<p>Expected Result: </p>'
            +'<p>Test passes if the blue rectangle could be drag and drop to the white box.</p>'
          +'</font>';
