var step = '<font class="fontSize">'
            +'<p>Purpose:</p>'
            +'<p>Verifies account permissions</p>'
            +'<p>Expected Result:</p>'
            +'<ol>'
            +'<li>Input pwd, the "guest" account can be switch successfully</li>'
            +'<li>The webapp should be installed successfully</li>'
            +'<li>The "app" account can be switch successfully</li>'
            +'<li>The wgt_sample_two webapp should not be listed</li>'
            +'</ol>'
          +'</font>';
