var step = '<font class="fontSize">'
            +'<p>Purpose:</p>'
            +'<p>Verifies that make_apk.py should be runnable from any location</p>'
            +'<p>Expected Result:</p>'
            +'<ol>'
            +'<li>Step 1</li>'
            +'<ol>'
            +'<li>Apk is generated successfully</li>'
            +'<li>Web app is installed successfully</li>'
            +'<li>Web app is launched successfully</li>'
            +'<li>Apk is generated successfully</li>'
            +'<li>Web app is installed successfully</li>'
            +'<li>Web app is launched successfully</li>'
            +'<li>Apk is generated successfully</li>'
            +'<li>Web app is installed successfully</li>'
            +'<li>Web app is launched successfully</li>'
            +'</ol>'
            +'<li>The results same as step 1</li>'
            +'</ol>'
          +'</font>';
