var step = '<font class="fontSize">'
            +'<p>Test Purpose: </p>'
            +'<p>Verifies the functionality of launching the Application which control by user instead of system. '
              +'Tests the two test Applications could be launched by App ID or customized AppControl\'s "operation" attribute by user.</p>'
            +'<p>Test Step: </p>'
            +'<ol>'
              +'<li>Click the "Install" button to install the custom package.</li>'
              +'<li>Click the "Launch" button to launch the custom package.</li>'
              +'<li>Click the "Install" button to install the regular package.</li>'
              +'<li>Click the "Launch" button to launch the regular package.</li>'
              +'<li>Click the "Uninstall" button to uninstall the two widgets.</li>'
            +'</ol>'
            +'<p>Expected Result: </p>'
            +'<p>Test passes if the test Applications launch successfully.</p>'
          +'</font>';
