var step = '<font style="font-size:85%">'
            +'<p>Check if data is successfully synchronized with an OMA DS server</p><br>'
            +'<p>Precondition: Pick one in &lt;Sample OMA DS Server List&gt; and add test contacts</p>'
            +'<p>&lt;Sample OMA DS Server List&gt;</p>'
            +'<p>- http://my.funambol.com/sync</p>'
            +'<p>- https://www.everdroid.com/web</p>'
            +'<p>- OMA DS 1.2 protocol Server</p><br>'
            +'<p>1. Fill in preset OMA DS Server, ID, Password and Database URI containing data to sync.<br>'
              +'For the Database URI field "OMA DS Server Database URI",<br>'
              +'- if you choose funambol OMA DS Server for this test, a tester needs to fill "card" string to the URI field.<br>'
              +'- if you choose everdroid OMA DS Server for this test, a tester needs to fill "con" string to the URI field.<br>'
              +'- if you are using other OMA DS Servers, then you need to go to the web page of the OMA DS Server which you use for the test.</p>'
            +'<p>2. Click Add Profile</p>'
            +'<p>3. Click Start Sync</p>'
            +'<p>4. Check the contacts are synchronized with the OMA DS server</p>'
          +'</font>';
