var step = '<font class="fontSize">'
            +'<p>Purpose:</p>'
            +'<ul>'
            +'<li>Verifies the nothing changes in the current working directory during a build</li>'
            +'<li>Verifies a working project directory can be created during the build for use later to create valid APKs</li>'
            +'<li>Verifies APK creation can be skipped if developer only wants to create a project directory for use later</li>'
            +'<ul>'
            +'<p>Expected Result:</p>'
            +'<ol>'
            +'<li>Create web app successfully</li>'
            +'<li>Display the created app project folder<br/>For example: --package=org.hello.tmptest, the folder in /tmp should be "Tmptest"'
            +'</li>'
            +'<li>Install the app successfully</li>'
            +'<li>Launch the app successfully</li>'
            +'<li>Run another two times successfully</li>'
            +'<li>Create one new project after the build in &lt;dest_dir&gt;/&lt;project_name&gt;</li>'
            +'<li>Display some set of key files, such as assets, bin, src and AndroidManifest.xml and so on</li>'
            +'<li>Build and exit successfully, no error message</li>'
            +'<li>Display &lt;project_name&gt;-release*.apk</li>'
            +'<li>Install the app successfully</li>'
            +'<li>Launch the app successfully</li>'
            +'<li>Display the error message like "--project-only must be used with --project-dir"</li>'
            +'<li>Display the folder &lt;dest_dir&gt;/&lt;project_name&gt;, no create apk package</li>'
            +'</ol>'
          +'</font>';
