var step = '<p>Purpose:</p>'
            +'<p>Verify that the shared mode app can download crosswalk library apk after configure</p>'
            +'<p>Expected Results:</p>'
            +'<ol>'
            +'<li>Build the apk successfully and create a project directory [dirname]</li>'
            +'<li>Display &lt;meta-data android:name="xwalk_apk_url" android:value="http://host/XWalkRuntimeLib.apk" &gt;</li>'
            +'<li>Display message "Please get Crosswalk Runtime Library"</li>'
            +'<li>Start to download the XWalkRuntimeLib.apk</li>'
            +'<li>Display "App installed"</li>'
            +'<li>Display the crosswalk main page</li>'
            +'</ol>';
