var step = '<font style="font-size:85%">'
            +'<p>Check if AppControls are supported</p><br>'
            +'<p>1. Select a thumbnail in the AppControl Image category</p>'
            +'<p>2. Check if the original image is displayed</p>'
            +'<p>3. Select a music file in the AppControl Audio category</p>'
            +'<p>4. Check if the music file is played</p>'
            +'<p>5. Select a video file in the AppControl Video category</p>'
            +'<p>6. Check if the video file is played</p>'
            +'<p>7. Select or Input the URL in the AppControl Browser category</p>'
            +'<p>8. Check if the URL is browsed</p>'
          +'</font>';
