var step = '<p>Purpose:</p>'
            +'<p>Verifies foo app can run successfully</p>'
            +'<p>Expected Result:</p>'
            +'<ol>'
            +'<li>Build org.test.foo successfully</li>'
            +'<li>Install the foo app successfully</li>'
            +'<li>Find the foo app successfully</li>'
            +'<li>Launch the foo app successfully</li>'
            +'<li>You can see "This is a Crosswalk Sample Application" on the device</li>'
            +'<li>Unistall the foo app successfully when the app running</li>'
            +'<li>Stop the foo app successfully</li>'
            +'<li>Unistall the foo app successfully</li>'
            +'<li>Uninstall AppTools and set the env successfully</li>'
            +'</ol>';
