var step = '<font class="fontSize">'
           + '<p>Test Purpose: </p>'
           + '<p>Verifies the device is able to handle pageVisible event when app page hidden/display.</p>'
           + '<p>Expected Result: </p>'
           + '<p>Test passes if the visibilitystate/hidden attribute is set to hidden/true for hidden state and visible/false for display state.</p>'
         + '</font>'
