var step = '<font class="fontSize">'
         + '<p>Test Purpose: </p>'
         + '<p>Verifies HTTP response header "Set-Cookie".</p>'
         + '<p>Test steps: </p>'
         + '<p>Check the "Set-Cookie" value.</p>'
         + '<p>Expected Result: </p>'
         + '<p>Test passes if it should get the response header value expect "Set-Cookie", the value of "Set-Cookie" should be null.</p>'
         + '</font>'
