var step = '<font class="fontSize">'
            +'<p>Purpose:</p>'
            +'<p>Verify the Crosswalk Cordova project can be import into the ADT tool</p>'
            +'<p>Expected Results:</p>'
            +'<ol>'
            +'<li>Open the eclipse</li>'
            +'<li>Open the menu</li>'
            +'<li>Open file browser window</li>'
            +'<li>Select the project</li>'
            +'<li>The project can import successfully</li>'
            +'<li>Analyze the error message and resolve</li>'
            +'<li>The project can build successfully and</li>'
            +'<ul>'
            +'<li>the LogCat display the apk debug message</li>'
            +'<li>the Console log display the apk install successfully</li>'
            +'</ul>'
            +'<li>The project can launch successfully</li>'
            +'<li>The project can build and launch successfully</li>'
            +'</ol>'
          +'</font>';
