var step = '<p>Purpose:</p>'
            +'<p>Verify that a dialog should pop-up asking the user whether he allows the application to use the API when a GeoLocation API is requested</p>'
            +'<p>Test Step: </p>'
            +'<ol>'
              +'<li>Click if a dialog pop-up asking the user whether he allows the application to use the computer\'s location when you enter this sample page the first time</li>'
              +'<li>Click the "Block"/"Allow" button</li>'
            +'</ol>'
            +'<p>Expected Result:</p>'
            +'<ol>'
            +'<li>A dialog for permission with "Block" and "Allow" button is shwon</li>'
            +'<li>If "Block" button is clicked, Page will shown "PERMISSION DENIED" and both the latitude and longitude return "n/a"</li>'
            +'<li>If "Allow" button is clicked, Both the latitude and longitude return the correct position data</li>'
            +'</ol>';
