var step = '<font class="fontSize">'
           + '<p>Test Purpose: </p>'
           + '<p>Verifies the 3D cube is drawn with red, yellow, blue, green and light blue colors, rotate smoothly and correctly. And tests the functionality of play and pause, rotate direction left or right, size of the cube from 1 to 5, rotate speed from 1 to 10 levels.</p>'
           + '<p>Test Step: </p>'
             + '<ol>'
               + '<li>Click the "Status" slider to play or pause the animation.</li>'
               + '<li>Click the "Direction" buttons to change the rotation direction.</li>'
               + '<li>Click the "Size" slider to change the animation size.</li>'
               + '<li>Click the "Speed" slider to change the rotation speed.</li>'
             + '</ol>'
           + '<p>Expected Result: </p>'
           + '<p>Test passes if all the check points work well during rotation.</p>'
         + '</font>'
