var step = '<font class="fontSize">'
            +'<p>Purpose:</p>'
            +'  <p>Verifies that city picker work well in crosswalk.</p>'
            +'<p>Pre-condition:</p>'
            +'<ul>'
            +'  <li>Conntect to network.</li>'
            +'</ul>'
            +'<p>Expected Result:</p>'
            +'<ol>'
            +'  <li>The apk is installed successfully</li>'
            +'  <li>The app is launched and Meituan.com is loaded</li>'
            +'  <li>The city can be selected and changed by city picker</li>'
            +'</ol>'
          +'</font>';
