var step = '<font class="fontSize">'
            +'<p>Purpose:</p>'
            +'<p>Verify the Cordova app page background color can be configured when build this app</p>'
            +'<p>Expected Results:</p>'
            +'<ol>'
            +'<li>The app can be installed successfully</li>'
            +'<li>The app can launch and run successfully</li>'
            +'<li>The app page\'s background color is red</li>'
            +'<li>Navigate to "https://crosswalk-project.org" page</li>'
            +'<li>The new page\'s background color is red</li>'
            +'<li>The app can exit successfully</li>'
            +'</ol>'
          +'</font>';
