var step = '<font class="fontSize">'
            +'<p>Test Purpose: </p>'
            +'<p>Check if can scan for media renderers and operate media renderers successfully</p>'
            +'<p>Precondition: </p>'
            +'<p>Make sure there is a media server in network<p/>'
            +'<p>Test Steps: </p>'
            +'<ol>'
              +'<li>Click the \'Scan for media renderers\', waiting for scaning media renderers successfully</li>'
              +'<li>Perform following operations for scanned media contents: \'Open\', \'Prefetch\', \'Play\', \'Pause\', \'Next\', \'Previous\', \'Mute\', \'Set Speed\', \'Set Volume\', \'Goto Track\', \'Cancel\', \'Stop\'</li>'
            +'</ol>'
            +'<p>Expected Result: </p>'
            +'<p>Test passes if scan for media renderers and operate media renderers successfully</p>'
          +'</font>';
