var step = '<font class="fontSize">'
            +'<p>Purpose:</p>'
            +'<p>Verify the Crosswalk package can build in defferent mode and arch</p>'
            +'<p>Expected Results:</p>'
            +'<ol>'
            +'<li>The script run successfully in command line, no error</li>'
            +'<li>There are "Build Package Successfully" and "Package Name Consistent" in command output.</li>'
            +'<li>The app is launched successfully</li>'
            +'<li>The app exit successfully</li>'
            +'<li>The app is uninstall successfully</li>'
            +'</ol>'
          +'</font>';
