var step = '<font class="fontSize">'
            +'<p>Purpose:</p>'
            +'  <p>Verifies that crosswalk network requests corporate network that uses proxy auto-config (PAC).</p>'
            +'<p>Pre-condition:</p>'
            +'<ul>'
            +'  <li>Android 5+ device(PAC support was added in Lollipop).</li>'
            +'  <li>Network wifi which is limited to access google.</li>'
            +'  <li>PAC which can access google.</li>'
            +'</ul>'
            +'<p>Expected Result:</p>'
            +'<ol>'
            +'  <li>Access Baidu successfully</li>'
            +'  <li>Access Google successfully</li>'
            +'</ol>'
          +'</font>';
