var step = '<font class="fontSize">'
         + '  <p>Test Purpose: </p>'
         + '  <p>Check if the network connection is supported</p>'
         + '  <p>Test Steps: </p>'
         + '    <ol>'
         + '      <li>When open the page or click the "Request" button, check if the communication can be succeed</li>'
         + '      <li>Click the "Release" button, check if the communication can be disconnected</li>'
         + '    </ol>'
         + '  <p>Expected Result: </p>'
         + '  <p>Test passes if the communication can be succeed and disconnected normally.</p>'
         + '</font>'
