var step = '<font class="fontSize">'
            +'<p>Purpose:</p>'
            +'<p>Verifies that enable web app gesture</p>'
            +'<p>Test steps:</p>'
            +'<ol>'
            +'<li>Click the button "Launch Test Page"</li>'
            +'<li>Scroll up screen</li>'
            +'<li>Scroll down screen</li>'
            +'</ol>'
            +'<p>Expected Result:</p>'
            +'<ol>'
            +'<li>Test page displayed successfully</li>'
            +'<li>Interface with gestures to scroll up successfully</li>'
            +'<li>Interface with gestures to scroll down successfully</li>'
            +'</ol>'
          +'</font>';
