var step = '<font class="fontSize">'
           + '<p>Test Purpose: </p>'
           + '<p>Verifies the device supports notification interface.</p>'
           + '<p>Test Step: </p>'
           + '<p>'
             + '<ol>'
               + '<li>'
                 + 'Click the "Show Notification" button.'
               + '</li>'
               + '<li>'
                 + 'Click the "Close Notification" button.'
               + '</li>'
             + '</ol>'
           + '</p>'
           + '<p>Expected Result: </p>'
           + '<p>Test passes if follow these scenario:</p>'
           + '<p>'
             + '<ol>'
               + '<li>'
                 + 'The Notification popup after step 1.'
               + '</li>'
               + '<li>'
                 + 'The Notification close after step 2.'
               + '</li>'
             + '</ol>'
           + '</p>'
         + '</font>'
