var step = '<font class="fontSize">'
            +'<p>Purpose:</p>'
            +'<p>Verifies that Packaging Tool minify css files with "--compressor=css" option</p>'
            +'<p>Expected Result:</p>'
            +'<ol>'
            +'<li>Apk could be created successfully</li>'
            +'<li>Extract the packaged apk successfully</li>'
            +'<li>Both the file size and content of style.css are different, style.css is minified</li>'
            +'</ol>'
          +'</font>';
