var step = '<font class="fontSize">'
           + '<p>Test Purpose: </p>'
           + '<p>Verifies the RTC connection can connect successfully, and transport data by peers.</p>'
           + '<p>Test Steps: </p>'
             + '<ol>'
               + '<li>Click the "Start Connect" button, to connect PC1 and PC2</li>'
               + '<li>When "pc1 and pc2 are connected successfully" display in the textarea above, input the message, click the "Send" button, to send message</li>'
               + '<li>Click the "Stop Connect" button, to close the connection</li>'
             + '</ol>'
           + '<p>Expected Result: </p>'
           + '<p>Peers(PC1 and PC2) can send message successfully.</p>'
         + '</font>'
