var step = '<font class="fontSize">'
            +'<p>Purpose:</p>'
            +'<p>Validate open dynamic external URL in system browser and open dynamic internal URL in app windows itself</p>'
            +'<p>Expected Result:</p>'
            +'<ol>'
            +'<li>The webapp install successfully and launch successfully.</li>'
            +'<li>Open internal URL in the app windows itself.</li>'
            +'<li>Open external URL in system browser.</li>'
            +'</ol>'
          +'</font>';
