var step = '<font class="fontSize">'
           + '<p>Test Purpose: </p>'
           + '<p>Verifies the device supports show presentation by clicking the "Request Show Presentation" button.</p>'
           + '<p>Precondition: </p>'
           + '<p>Turn on "Simulate Secondary Display" by "Setting" app.</p>'
           + '<p>Test Step: </p>'
           + '<p>'
             + '<ol>'
               + '<li>'
                 + 'Click the "Request Show Presentation" button.'
               + '</li>'
               + '<li>'
                 + 'Click the "Close Presentation" button.'
               + '</li>'
             + '</ol>'
           + '</p>'
           + '<p>Expected Result: </p>'
           + '<p>Test passes if an presention window show on wirless display after step 1, and presention window close after step 2.</p>'
         + '</font>'
