var step = '<p>Test Purpose: </p>'
            +'<p>Verifies the functionality of three sharedmode apps can work well.</p>'
            +'<p>Expected Results: </p>'
            +'<ol>'
            +'<li>Launch web app failed and prompt: Please get Crosswalk Runtime Library</li>'
            +'<li>Launch web app failed and prompt: Please get Crosswalk Runtime Library</li>'
            +'<li>Install the Crosswalk Runtime Library successfully</li>'
            +'<li>Display the baidu main page</li>'
            +'<li>Display the crosswalk main page</li>'
            +'<li>Display the hao123 main page</li>'
            +'</ol>';
