var step = '<font class="fontSize">'
            +'<p>Pre-condition: </p>'
            +'<ol>'
            +'<li>Chrome is availabled.</li>'
            +'</ol>'
            +'<p>Purpose:</p>'
            +'<p>Verifies the remode debugging can enable and disable successfully</p>'
            +'<p>Expected Result:</p>'
            +'<ol>'
            +'<li>Remote debugging enabled at port "9222" successfully</li>'
            +'<li>sdb port forward "9222" successfully</li>'
            +'<li>Webapp can be launch successfully with debuggable mode off</li>'
            +'<li>Should not inspect the Webapp successfully</li>'
            +'<li>Webapp can be launched with debuggable mode on</li>'
            +'<li>The page is showing Inspectable App ,inspectable link and thumbnail(white box,as chrome thumbnail)</li>'
            +'<li>The inspectable app page open successfully</li>'
            +'<li>Remote debugging disabled successfully</li>'
            +'<li>Should not inspect the app successfully</li>'
            +'<li>Launch tizen app successful</li>'
            +'<li>Open a new window loaded with the url</li>'
            +'<li>The json key faviconUrl has corresponding value.</li>'
            +'</ol>'
          +'</font>';
