var step = '<font class="fontSize">'
            +'<p>Test Purpose: </p>'
            +'<p>Verify if the viewport functionality of setting customized height and width, device height and width, scale, enabling or disabling user scalable to allow or disallow zoom in/out screen, sliding the screen by figure work well.</p>'
            + '<p>Test Step: </p>'
            + '<p>'
              + '<ol>'
                + '<li>'
                  + 'Launch sub app "ViewportTest".'
                + '</li>'
                + '<li>'
                  + 'Click the button in "ViewportTest" to test Viewport.'
                + '</li>'
              + '</ol>'
            + '</p>'
            +'<p>Expected Result: </p>'
            +'<p>Test passes if the viewport functionality of setting customized height and width, device height and width, scale, enabling or disabling user scalable to allow or disallow zoom in/out screen, sliding the screen by figure work well.</p>'
          +'</font>';
