var step = '<font class="fontSize">'
            +'<p>Expected results</p>'
            +'<ol>'
            +'<li>Install app successfully, no error, no warning message</li>'
            +'<li>You will see a normal green icon with text "Manifest GIF" and the version is "1.0.1"</li>'
            +'<li>Display "Splash Screen Portrait" with green background in Splash Screen after launch the app successfully</li>'
            +'<li>Display some descriptions about manifest configuration with portrait screen</li>'
            +'<li>Display status bar</li>'
            +'</ol>'
            +'<p>This sample demonstrates manifest members "icons", "xwalk_version" "orientation", "display", "xwalk_launch_screen"</p>'
            +'<ul>'
            +'<li>App configure values include: gif format icons, three digits version, portrait orientation, standalone display, user-interactive ready_when and portrait</li>'
            +"<li>Standalone: In this mode, the application displays in the same manner as a native application. The standard UI elements from the context (e.g. the device's status bar) remain visible</li>"
            +'<li>Xwalk_launch_screen members'
            +'<ul>'
            +'<li>Ready_when: The application readiness state at which to hide the launch screen'
            +'<ul>'
            +'<li>User-interactive:'
            +'<ul>'
            +'<li>The first visually non-empty paint has occurred</li>'
            +'<li>The DOM and CSSOM have been constructed</li>'
            +'</ul>'
            +'</li>'
            +'</ul>'
            +'</li>'
            +'<li>Portrait: The launch screen to use for portrait mode</li>'
            +'</ul>'
            +'</li>'
            +'</ul>'
          +'</font>';
