var step = '<font class="fontSize">'
            +'<p>Expected results</p>'
            +'<ol>'
            +'<li>Install app successfully, no error, no warning message</li>'
            +'<li>You will see a normal turquoise icon with text "Manifest BMP"</li>'
            +'<li>Display "Splash Screen Landscape" with turquoise background and landscape screen after launch the app successfully</li>'
            +'</ol>'
            +'<p>This sample demonstrates manifest members "icons", "xwalk_app_version", "orientation", "display"</p>'
            +'<ul>'
            +'<li>App configure values include: bmp format icons, landscape orientation, broswer display, custom ready_when</li>'
            +'<li>Broswer: Opens the web application using the platform-specific convention for opening hyperlinks in the user agent (e.g., in a browser tab or a new window)</li>'
            +'</ul>'
          +'</font>';
