var step = '<font class="fontSize">'
            +'<p>Expected results</p>'
            +'<ol>'
            +'<li>Install app successfully, no error, no warning message</li>'
            +'<li>Display text "Manifest BMP" with turquoise background normally and the version value as "1.0.0.120150101"</li>'
            +'<li>Launch the app successfully and display "Splash Screen Landscape" with turquoise background and landscape screen</li>'
            +'<li>The screen always stay the loading page</li>'
            +'</ol>'
            +'<p>This sample demonstrates manifest members "icons", "xwalk_version", "orientation", "display", "xwalk_launch_screen"</p>'
            +'<ul>'
            +'<li>Test values include: bmp format icons, four digits version, landscape orientation, broswer display, custom ready_when</li>'
            +'<li>Broswer: Opens the web application using the platform-specific convention for opening hyperlinks in the user agent (e.g., in a browser tab or a new window)</li>'
            +'<li>Xwalk_launch_screen members'
            +'<ul>'
            +'<li>Ready_when: The application readiness state at which to hide the launch screen</li>'
            +'<ul>'
            +'<li>Custom:'
            +'<ul>'
            +'<li>The first visually non-empty paint has occurred</li>'
            +'<li>The window.screen.show() method was called</li>'
            +'</ul>'
            +'</li>'
            +'</ul>'
            +'</ul>'
            +'</li>'
            +'</ul>'
          +'</font>';
