var step = '<font class="fontSize">'
            +'<p>Test Steps:</p>'
            +'<ol>'
            +'<li>Click the color picker button</li>'
            +'<li>Select the different color in the color picker window</li>'
            +'</ol>'
            +'<p>Expected Result:</p>'
            +'<ol>'
            +'<li>Display a color picker window</li>'
            +'<li>The color of the color picker button is changed successfully</li>'
            +'</ol>'
          +'</font>';
