var step = '<font class="fontSize">'
           + '<p>Test Purpose: </p>'
           + '<p>Verifies setUserAgentString and removeAllCookies methods are valid.</p>'
           + '<p>Test Steps: </p>'
             + '<ol>'
               + '<li>Click "set user agent string" button, check if set user agent string sucess.</li>'
               + '<li>Click "remove all cookies" button, check if cookies saved for application have been removed.</li>'
             + '</ol>'
           + '<p>Expected Result: </p>'
           + '<p>Test passes if set user agent string sucess and remove cookies success.</p>'
         + '</font>'
