var step = '<font class="fontSize">'
            +'<p>Purpose:</p>'
            +'<p>Verifies the windows management basic features</p>'
            +'<p>Expected Result:</p>'
            +'<ol>'
            +'<li>The app button is on the task bar</li>'
            +'<li>Pin this app button to the task bar successfully</li>'
            +'<li>The app page hide</li>'
            +'<li>The app page show</li>'
            +'<li>Exit the app successfully</li>'
            +'<li>Launch the app successfully</li>'
            +'<li>Unpin this app button to the task bar successfully</li>'
            +'</ol>'
          +'</font>';
