var step = '<font class="fontSize">'
            +'<p>Purpose:</p>'
            +'<p>Verify the Cordova package can build, install and launch successfully</p>'
            +'<p>Expected Results:</p>'
            +'<ol>'
            +'<li>The command run successfully, no error</li>'
            +'<li>The console display "Build Package Successfully" and "Package Name Consistent"</li>'
            +'<li>There is no "_beta" appended "org.xwalk:xwalk_core_library" in xwalk.gradle file</li>'
            +'<li>The app is running normally</li>'
            +'<li>The app can exit successfully</li>'
            +'<li>The app can be uninstalled successfully</li>'
            +'</ol>'
          +'</font>';
