var step = '<p>Purpose:</p>'
            +'<p>Set image to container photo/color/depth/raw depth image.</p>'
            + '<p>Test Steps: </p>'
              + '<ol>'
                + '<li>Click the "Take Photo" button</li>'
                + '<li>Click the "Set Container Image" button</li>'
                + '<li>Click the "Set Color Image" button</li>'
                + '<li>Click the "Set Depth Image" button</li>'
                + '<li>Click the "Set Raw Depth Image" button</li>'
              + '</ol>'
            +'<p>Expected Result:</p>'
              +'<ol>'
                +'<li>There is a photo showed on the right after click "Take Photo" button</li>'
                +'<li>The right photo is replaced by new one and status shows "set container image succeed" '
                +'after click "Set Container Image" button</li>'
                +'<li>Status shows "set color image succeed" after click "Set Color Image" button</li>'
                +'<li>Status shows "set depth image succeed" after click "Set Depth Image" button</li>'
                +'<li>Status shows "set raw depth image succeed" after click "Set Raw Depth Image" button</li>'
              +'</ol>';
