var step = '<font class="fontSize">'
           + '<p>Test Purpose: </p>'
           + '<p>Verifies the file can be created and read</p>'
           + '<p>Test Steps: </p>'
             + '<ol>'
               + '<li>Write content in the above textarea, and click the "create file"</li>'
               + '<li>Click the "read file"</li>'
             + '</ol>'
           + '<p>Expected Result: </p>'
           + '<p>Test passes if the content in the above textarea can be read into the below textarea</p>'
         + '</font>'
