var step = '<font class="fontSize">'
            +'<p>Purpose:</p>'
            +'<p>Verifies that extension_manager.py should work properly</p>'
            +'<p>Expected Result:</p>'
            +'<ol>'
            +'<li>The file "&lt;path to extension_manager.py&gt;/extensions/crosswalk-android-extensions/out/Default/gen/iap/iap.jar" exists</li>'
            +'<li>Display "+ crosswalk-android-extensions/iap" successfully</li>'
            +'<li>Display "+ crosswalk-android-extensions/iap" successfully</li>'
            +'<li>Display "- crosswalk-android-extensions/iap" successfully</li>'
            +'<li>Display "+ crosswalk-android-extensions/iap" successfully</li>'
            +'<li>Generated apk successfully, no error message</li>'
            +'<li>Remove the path "&lt;path to extension_manager.py&gt;/extensions/crosswalk-android-extensions" successfully</li>'
            +'</ol>'
          +'</font>';
