var step = '<font class="fontSize">'
            +'<p>Expected results</p>'
            +'<ol>'
            +'<li>Install app successfully, no error, no warning message</li>'
            +'<li>You will see a normal blue icon with text "Manifest PNG" , the version is "1.0" and the name is "manifest_demo_1"</li>'
            +'<li>Display "Splash Screen Auto" with blue background in Splash Screen after launch the app successfully</li>'
            +'<li>Display some descriptions about fullscreen screen</li>'
            +'<li>Switch the screen normally</li>'
            +'</ol>'
            +'<p>This sample demonstrates manifest members "icons", "xwalk_version", "orientation", "display", "xwalk_launch_screen"</p>'
            +'<ul>'
            +'<li>App configure values include: png format icons, two digits version, default orientation, fullscreen display, complete ready_when and default</li>'
            +"<li>Fullscreen: In this mode, the application is displayed so that it fills the entire area of the screen, with none of the runtime's UI elements ('chrome') visible</li>"
            +'<li>Xwalk_launch_screen members'
            +'<ul>'
            +'<li>Ready_when: The application readiness state at which to hide the launch screen</li>'
            +'<ul>'
            +'<li>Complete:'
            +'<ul>'
            +'<li>The first visually non-empty paint has occurred</li>'
            +'<li>All the resources have been loaded</li>'
            +'</ul>'
            +'</li>'
            +'</ul>'
            +'<li>Default: The launch screen to use for both landscape and portrait mode</li>'
            +'</ul>'
            +'</li>'
            +'</ul>'
          +'</font>';
