var step = '<font class="fontSize">'
            +'<p>Purpose:</p>'
            +'<p>Verify the CROSSWALK_ANDROID_COMMANDLINE config feature</p>'
            +'<p>Expected Results:</p>'
            +'<ol>'
            +'<li>The app can be installed successfully</li>'
            +'<li>The app can launch and run successfully</li>'
            +'<li>The app page does not refresh and not cause ugly behaviour</li>'
            +'<li>There are green "Pass" below "Disable WebGL" and "Disable WebRTC" on the app page</li>'
            +'</ol>'
          +'</font>';
