var step = '<font style="font-size:85%">'
        + '<p>Test Purpose: </p>'
        + '<p>Verifies the device supports tizen vehicle information access API.</p>'
        + '<p>Test Step: </p>'
        + '<p>'
          + '<ol>'
            + '<li>'
              + 'Click the "Get vehicle" button.'
            + '</li>'
            + '<li>'
              + 'Click the "Set vehicle door" button.'
            + '</li>'
          + '</ol>'
        + '</p>'
        + '<p>Expected Result: </p>'
        + '<p>Test passes if the detected direction reflects the actual vehicle information after step 1, and show "Set door lock success" after step 2.</p>'
      + '</font>'
