var step = '<font class="fontSize">'
            +'<p>Test Purpose: </p>'
            +'<p>Verifies functionality of mediaserver work well.</p>'
            +'<p>Precondition: </p>'
            +'<p>Make sure there is a dlna mediaserver in network.<p/>'
            +'<p>Test Step: </p>'
            +'<p>1. Click the button "Scan media servers", if there is no "Browse root container of iMediaExport" display.</p>'
            +'<p>2. Click the button "Browse root container of iMediaExport", then there will have five buttons.</p>'
            +'<p>3. Click the five buttons, then there will display contents.</p>'
            +'<p>Expected Result: </p>'
            +'<p>Test passes if all the above steps are pass.</p>'
          +'</font>';
