var step = '<font class="fontSize">'
            +'<p>Test Purpose: </p>'
            +'<p>Verifies the content API is supported and valid.</p>'
            +'<p>Test Steps: </p>'
            +'<ol>'
              +'<li>Click the \'Open Dir\'</li>'
              +'<li>Click the \'GETFILES\' behind directories</li>'
              +'<li>Click the \'SCANFILE\' behind file list</li>'
            +'</ol>'
            +'<p>Expected Result: </p>'
            +'<p>Test passes if the directories, file list and scan result can show normally and correctly.</p>'
          +'</font>';
