var step = '<p>Purpose:</p>'
            +'<p>Verify that the demo CordovaPluginFileDemo can build succeeded and work well on test device</p>'
            +'<p>Expected Results:</p>'
            +'<ol>'
            +'<li>Open the app named "Xcode" and display one project named "CordovaPluginFileDemo" on the left"</li>'
            +'<li>Display message "Build Succeeded" and running the build app</li>'
            +'<li>Launch the app named like "CordovaPluginFileDemo" successfully, no error message and no crash</li>'
            +'<li>Display some message about the input content</li>'
            +'<li>Display the input content</li>'
            +'<li>Delete successfully</li>'
            +'</ol>';
