var step = '<font class="fontSize">'
            +'<p>Purpose:</p>'
            +'<p>Verifies that the WebApp common operation and version update</p>'
            +'<p>Expected Result:</p>'
            +'<ol>'
            +'<li>The wgt WebApp is launched as landscape mode successfully and splash image is showing when launching the WebApp</li>'
            +'<li>The context menu should be displayed when the user long-presses text </li>'
            +'<li>The widget version is 1.0.0.1</li>'
            +'<li>The widget is installed successfully, version update to 1.0.0.2 and src is www.baidu.com</li>'
            +'<li>The WebApp is uninstalled successfully</li>'
            +'<li>The WebApp with invalid signature file should not be installed successfully</li>'
            +'<li>The WebApp with valid signature file is installed successfully</li>'
            +'<li>The WebApp with valid signature file is uninstalled successfully</li>'
            +'</ol>'
          +'</font>';
