var step = '<p>Purpose:</p>'
            +'<p>Verify the test app can initialize normally after restart it</p>'
            +'<p>Expected Results:</p>'
            +'<ol>'
            +'<li>Launch web app successfully</li>'
            +'<li>React quickly and display "TestItem" under the "Test" after the first time click, no delay and slow response</li>'
            +'<li>Display text "This is a test page"</li>'
            +'<li>Launch web app successfully, no crash and error message</li>'
            +'<li>The expected result same as step 2 and 3</li>'
            +'</ol>';
