var step = '<font class="fontSize">'
        + '<p>Test Purpose: </p>'
        + '<p>Verifies SpeechSynthesis realated interface work well.</p>'
        + '<p>Pre-condition: </p>'
          + '<ol>'
            + '<li>Requires the network connection that could connect to speech synthesis service.</li>'
          + '</ol>'
        + '<p>Test steps: </p>'
          + '<ol>'
            + '<li>Press "start" button to speak the default text, you can input text if you want to.</li>'
            + '<li>Press "cancel" button to stop the sound.</li>'
            + '<li>Press "pause" button to pause the sound.</li>'
            + '<li>Press "resume" button to resume the sound.</li>'
          + '</ol>'
        + '<p>Expected Result: </p>'
          + '<ol>'
            + '<li>Can hear a sound and its content must match with the text by "start" button.</li>'
            + '<li>Can stop the sound by "cancel" button.</li>'
            + '<li>Can pause the sound by "pause" button.</li>'
            + '<li>Can resume the sound by "resume" button.</li>'
          + '</ol>'
      + '</font>';
