var step = '<font class="fontSize">'
            +'<p>Purpose:</p>'
            +'<p>Verifies that Crosswalk enable update web app with the different app-version.</p>'
            +'<p>Expected Result:</p>'
            +'<ol>'
            +'<li>Apk could be created successfully</li>'
            +'<li>Web App could be installed successfully</li>'
            +'<li>Web App could be launched successfully</li>'
            +'<li>Web App version is 1.0.0</li>'
            +'<li>Apk could be created correctly</li>'
            +'<li>Web App could be updated successfully</li>'
            +'<li>Web App could be launched successfully</li>'
            +'<li>Web App version is 1.0.1</li>'
            +'</ol>'
          +'</font>';
