var step = '<p>Test Purpose: </p>'
            +'<p>Verifies the Crosswalk Runtime Library can redownload and install after disturb the process during download the Library by disable network</p>'
            +'<p>Expected Results: </p>'
            +'<ol>'
            +'<li>Launch web app failed and prompt: Please get Crosswalk Runtime Library</li>'
            +'<li>Start to download the Crosswalk Runtime Library</li>'
            +'<li>Terminated the download process</li>'
            +'<li>Start to download the Crosswalk Runtime Library again</li>'
            +'<li>Downloaded the Crosswalk Runtime Library and install it successfully</li>'
            +'</ol>';
