var step = '<font class="fontSize">'
            + '<p>Test Purpose: </p>'
            + '<p>Verifies the device supports single touch, two fingers touch and three fingers touch by clicking the blue images.</p>'
            + '<p>Test Step: </p>'
            + '<p>'
              + '<ol>'
                + '<li>'
                  + 'Touch one blue image with one finger.'
                + '</li>'
                + '<li>'
                  + 'Touch two blue images with two fingers.'
                + '</li>'
                + '<li>'
                  + 'Touch three blue images with three fingers.'
                + '</li>'
              + '</ol>'
            + '</p>'
            + '<p>Expected Result: </p>'
            + '<p>Test passes if all the tips "one button touched, two buttons touched at one time, three buttons touched at one time" show.</p>'
          + '</font>'
