var step = '<font class="fontSize">'
            +'<p>Purpose:</p>'
            +'<p>Verify the Cordova package can remote debug successfully</p>'
            +'<p>Expected Results:</p>'
            +'<ol>'
            +'<li>There is a RD-debug.apk under remotedebugging/bin folder and the app is launched</li>'
            +'<li>A "com.example.remotedebugging" app display in the inspection page</li>'
            +'<li>The inspection options display in page</li>'
            +'<li>The app sources code is loaded, and display Debug information, such as "Breakpoints" "DOM Breakpoints"</li>'
            +'<li>The breakpoint is added</li>'
            +'<li>The html code of current page is loaded</li>'
            +'<li>Display shortcut menu</li>'
            +'<li>The source code could be changed</li>'
            +'<li>The change takes effect</li>'
            +'</ol>'
          +'</font>';
