var step = '<font class="fontSize">'
            +'<p>Test Purpose: </p>'
            +'<p>Verifies the callhistory is supported and valid.</p>'
            +'<p>Test Steps: </p>'
            +'<ol>'
              +'<li>Open the page or click the \'Refresh\'</li>'
              +'<li>Click the \'Remove\'</li>'
            +'</ol>'
            +'<p>Expected Result: </p>'
            +'<p>Test passes if the callhistory can be got and removed normally.</p>'
          +'</font>';
