var step = '<font class="fontSize">'
        + '<p>Test Purpose: </p>'
        + '<p>Check if methods of the sso supported</p>'
        + '<p>Test Steps: </p>'
          + '<ol>'
            + '<h4>The first table: </h4>'
            + '<li>click the "Query Methods" button, check if the queryMethods() can be succeeded and show in the textarea box.</li>'
            + '<li>input a string to the input box and then click the "Query Mechanisms" button, check if the queryMechanisms() can be succeeded and show in the textarea box.</li>'
            + '<li>input a string to the input box and then click the "Query Identities" button, check if the queryIdentities() can be succeeded and show in the textarea box.</li>'
            + '<li>input a string to the input box and then click the "Get Identity" button, check if the getIdentity() can be succeeded and show in the textarea box.</li>'
            + '<li>click the "Clear DB" button, check if the clearDB() can clear successful and existing identity will be cleared.</li>'
          + '</ol>'
          + '<ol>'
            + '<h4>The second table: </h4>'
            + '<li>First input infomation to the input box follow the prompts.</li>'
            + '<li>Then click the "Create Identity" button, check if identity can be added with jsid of identity and show in the textarea box.</li>'
            + '<li>Modify the infomation and then click the "Update Identity" button, check if updated succeeded and show in the textarea box.</li>'
          + '</ol>'
          + '<ol>'
            + '<h4>The third table: </h4>'
            + '<li>input a string to the input box and then click the "Start Session" button, check if the session can be added and show in the textarea box.</li>'
            + '<li>input a string to the input box and then click the "Update Credentials" button, check if the requestCredentialsUpdate() can be succeeded and show in the textarea box.</li>'
            + '<li>click the "Store" button, check if the store succeeded and show in the textarea box</li>'
            + '<li>input a string to the input box and then click the "Add Reference" button, check if the reference can be added and show in the textarea box.</li>'
            + '<li>input a string to the input box and then click the "Remove Reference" button, check if the reference can be removed and show in the textarea box.</li>'
            + '<li>click the "Remove" button, check if the identity can be removed and show in the textarea box</li>'
            + '<li>click the "Signout" button, check if can sign out and show in the textarea box</li>'
          + '</ol>'
          + '<ol>'
            + '<h4>The fourth table: </h4>'
            + '<li>input a string to the input box and then click the "QueryAvailableMechanisms" button, check if the queryAvailableMechanisms() can be succeeded and show in the textarea box.</li>'
            + '<li>input infomation to the input box follow the prompts and then click the "challenge" button, check if the challenge() can be succeeded and show in the textarea box.</li>'
            + '<li>click the "cancel" button, check if the cancel() can be succeeded and the session can be removed.</li>'
          + '</ol>'
        + '<p>Expected Result: </p>'
        + '<p>Test passes if methods of the sso can be implemented successfully.</p>'
      + '</font>'
