var step = '<p>Purpose:</p>'
            +'<p>Verify that Crosswalk shared mode app can get matched Crosswalk runtime library from Google Play store or PRC store.</p>'
            +'<p>Expected Results:</p>'
            +'<ol>'
            +'<li>The app is started, and pop up get crosswalk dialog.</li>'
            +'<li>Crosswalk runtime is installed via Google Play store or other PRC store.</li>'
            +'<li>The app is launched successfully.</li>'
            +'<li>The Crosswalk runtime name matched in table can be found by command line.</li>'
            +'<li>The Crosswalk runtime is uninstalled successfully.</li>'
            +'</ol>';
