var step = '<font class="fontSize">'
            +'<p>Test Purpose:</p>'
            +'<p>Verifies getUserMedia works well with audio</p>'
            +'<p>Test Steps:</p>'
            +'<ol>'
              +'<li>Click "Start Mic" to launch mic, speak some voices to the mic</li>'
              +'<li>Click "Stop Play" to pause audio</li>'
            +'</ol>'
            +'<p>Expected Result:</p>'
            + '<ol>'
              + '<li>Audio is playing, can hear a sound and its content must match what you speak to the mic</li>'
              + '<li>Audio play is paused</li>'
            + '</ol>'
          +'</font>';
