var step = '<font class="fontSize">'
            +'<p>Purpose:</p>'
            +'<p>Verifies that enable open a file with third part app</p>'
            +'<p>Pre-condition:</p>'
            +'<ul>'
            +'<li>Install WPS or other thirdpart app to open docx/png/pdf file</li>'
            +'<li>Make sure there is a sdcard folder named "/mnt/sdcard1" in test device</li>'
            +'</ul>'
            +'<p>Expected Result:</p>'
            +'<ol>'
            +'<li>The web app is launched successfully</li>'
            +'<li>DOCX file can be opened successfully</li>'
            +'<li>PNG file can be opened successfully</li>'
            +'<li>PDF file can be opened successfully</li>'
            +'</ol>'
          +'</font>';
