var step = '<p>Purpose:</p>'
            +'<p>Verify that the demo CordovaPluginDeviceDemo can build succeeded and work well on test device</p>'
            +'<p>Expected Results:</p>'
            +'<ol>'
            +'<li>Open the app named "Xcode" and display one project named like "CordovaPluginDeviceDemo" on the left"</li>'
            +'<li>Display message "Build Succeeded" and running the build app</li>'
            +'<li>Launch the app named like "CordovaPluginDeviceDemo" successfully, no error message and no crash</li>'
            +'<li>Display some names about the test device such as: available, platform, version and so on</li>'
            +'<li>Display the correct value about the test device</li>'
            +'</ol>';
