var step = '<p>Purpose:</p>'
            +'<p>Verify that the demo CordovaPluginDeviceDemo can build succeeded and work well on test device</p>'
            +'<p>Expected Results:</p>'
            +'<ol>'
            +'<li>Open the app named "Xcode" and display one project named like "CordovaPluginDeviceDemo" on the left, include two subprojects "Cordova.xcodeproj" and "XWalkView.xcodeproj"</li>'
            +'<li>Display message "Build Succeeded"</li>'
            +'<li>Launch the app named like "CordovaPluginDeviceDemo" successfully, no error message and no crash</li>'
            +'<li>Display the correct value</li>'
            +'<li>Display the correct value</li>'
            +'</ol>';
