var step = '<font class="fontSize">'
           + '<p>Test Purpose: </p>'
           + '<p>Verifies the mark and measure method can calculate the time of a task.</p>'
           + '<p>Test Steps: </p>'
             + '<ol>'
               + '<li>Input some number to the text box</li>'
               + '<li>Click the "Calculator"</li>'
             + '</ol>'
           + '<p>Expected Result: </p>'
           + '<p>Test passes if the Start Time and Duration Time can be get.</p>'
         + '</font>'
