var step = '<font class="fontSize">'
            +'<p>Purpose:</p>'
            +'<p>Verifies that pdf file can be downloaded successfully</p>'
            +'<p>Expected Result:</p>'
            +'<ol>'
            +'<li>Having a notification telling that the file is being downloaded.</li>'
            +'<li>Having another notification telling that the file has finished downloading.</li>'
            +'<li>Having a notification with the downloaded file that can tap to open the downloaded file.</li>'
            +'</ol>'
          +'</font>';
