var step = '<font class="fontSize">'
           + '<p>Test Purpose: </p>'
           + '<p>Verifies the device is able to handle pageVisible event when lock and unlock the screen by gesture.</p>'
           + '<p>Expected Result: </p>'
           + '<p>Test passes if the screen lock and unlock information displayed correctly and no "Fail" appears on screen.</p>'
         + '</font>'
