var step = '<font class="fontSize">'
            +'<p>Purpose:</p>'
            +'<p>Verifies that options help and version of packer tool work properly</p>'
            +'<p>Expected Result:</p>'
            +'<ol>'
            +'<li>The help info is displayed in the terminal normally</li>'
            +'<li>The help info is displayed in the terminal normally</li>'
            +'<li>The version info is displayed in the terminal normally</li>'
            +'<li>The displayed version is the same with the Crosswalk version</li>'
            +'<li>The version info is displayed in the terminal normally</li>'
            +'<li>The displayed version is the same with the Crosswalk version</li>'
            +'</ol>'
          +'</font>';
