var step = '<font style="font-size:85%">'
            +'<p>Test Purpose: </p>'
            +'<p>Verifies the CSS two boxes: </p>'
            +'<p>1. Color is changing in order of green, pink, blue, green, red, green; </p>'
            +'<p>2. Square/Circle move with 20 degree direction from left to right; </p>'
            +'<p>3. About rotate direction from left to right, square is rotate in 2D(180degree), circle is rotate in 3D(Y-axis); </p>'
            +'<p>4. Square/circle is transfering between square/circle when moving from right to left; </p>'
            +'<p>5. About font type, "SQUARE" is black, "CIRCLE" is white; </p>'
            +'<p>6. About frame box border, style is outset in green, with gray shadow. </p>'
            +'<p>Expected Result: </p>'
            +'<p>This test PASS only if the transformation and animation function well follow above 6 rules.</p>'
          +'</font>';
