var step = '<font style="font-size:85%">'
           + '<p>Check NFC communication</p><br>'
           + '<p>1. Fill in NFC Write Message</p>'
           + '<p>2. Click Write to card and Place the NFC Tag to device</p>'
           + '<p>3. Check the Write Message</p>'
           + '<p>4. Click Read from card and Place the NFC Tag to device</p>'
           + '<p>5. Check the Read Message</p>'
           + '<p>6. Click Communicate with another device and Connected two device which are operated NFC</p>'
           + '<p>7. Check the Receive Message</p>'
         + '</font>'
