var step = '<font class="fontSize">'
            +'<p>Purpose:</p>'
            +'<p>Verifies that enable security url certificate</p>'
            +'<p>Pre-condition:</p>'
            +'<ul>'
            +'<li>Connect to network</li>'
            +'</ul>'
            +'<p>Test Steps:</p>'
            +'<ol>'
            +'<li>Click the link "Open Website"</li>'
            +'<li>Click the button "OK"</li>'
            +'</ol>'
            +'<p>Expected Result:</p>'
            +'<ol>'
            +'<li>There will display Ssl Certification Error Alert</li>'
            +'<li>There will display the website, and some textarea and buttons in screen</li>'
            +'</ol>'
          +'</font>';
