var step = '<font class="fontSize">'
           + '<p>Test Purpose: </p>'
           + '<p>Verifies the table can be set colors by querySelector or querySelectorAll.</p>'
           + '<p>Test Steps: </p>'
             + '<ol>'
               + '<li>Click the "querySelector" button</li>'
               + '<li>Click the "querySelectorAll" button</li>'
             + '</ol>'
           + '<p>Expected Result: </p>'
           + '<p>Test passes if the table can be set green</p>'
         + '</font>'
