var step = '<font class="fontSize">'
           + '<p>Test Purpose: </p>'
           + '<p>Verifies network connection well, performance metrics data of loading image.</p>'
           + '<p>Test Steps: </p>'
             + '<ol>'
               + '<li>Connect to an available network</li>'
               + '<li>Click the "Load image" button</li>'
             + '</ol>'
           + '<p>Expected Result: </p>'
           + '<p>Test passes if performance metrics data of loading image will display on the page.</p>'
         + '</font>'
