var step = '<font style="font-size:85%">'
            +'<p>Test Steps: </p>'
            +'<ol>'
            +'<li>1. Click "Unoverlapped"</li>'
            +'<li>2. Click "Overlapped"</li>'
            +'<li>3. Click "Interstitial"</li>'
            +'</ol>'
            +'<p>Expected Results: </p>'
            +'<ol>'
            +'<li>1. Create an unoverlapped advertising</li>'
            +'<li>2. Create a overlapped advertising</li>'
            +'<li>3. Create a interstitial advertising</li>'
            +'</ol>'
          +'</font>';
