var step = '<font class="fontSize">'
            +'<p>Purpose:</p>'
            +'<p>Verify the AdMob plugin can work well</p>'
            +'<p>Test Steps:</p>'
            +'<li>Click "create Ad" button if there is no Ad shown</li>'
            +'<li>Click "hide Ad" button</li>'
            +'<li>Click "show Ad" button</li>'
            +'<li>Click "remove Ad" button</li>'
            +'<li>Click "create Interstitial Ad" and "show Interstitial Ad" button</li>'
            +'<p>Expected Result:</p>'
            +'<li>The Ad can be created</li>'
            +'<li>The Ad can be hidden</li>'
            +'<li>The Ad can be shown</li>'
            +'<li>The Ad can be removed</li>'
            +'<li>The interstitial Ad can be shown</li>'
          +'</font>';
