var step = '<p>Test Purpose: </p>'
            +'<p>Verify the Crosswalk Runtime Library can download twice with config url method in two sharedmode apps at the same time(test for config url)</p>'
            +'<p>Verify the Crosswalk Runtime Library can not download twice from google play in two sharedmode apps at the same time(test for google play)</p>'
            +'<p>Expected Results: </p>'
            +'<ol>'
            +'<li>Launch web app failed and prompt: Please get Crosswalk Runtime Library</li>'
            +'<li>Start to download the Crosswalk Runtime Library</li>'
            +'<li>Launch web app failed and prompt: Please get Crosswalk Runtime Library</li>'
            +'<li>The app can download twice at the same time(config url)</li>'
            +'<li>The app can not download twice at the same time, display the downloading progress bar at the first time(google play)</li>'
            +'</ol>';
