var step = '<font class="fontSize">'
            +'<p>Test Purpose: </p>'
            +'<p>Verifies the device supports the method of requestAnimationFrame and cancelRequestAnimationFrame.</p>'
            +'<p>Test Step: </p>'
            +'<ol>'
              +'<li>Click the "Start" button to move the blue box.</li>'
              +'<li>Click the "Stop" button to stop the moving blue box.</li>'
            +'</ol>'
            +'<p>Expected Result: </p>'
            +'<p>Test passes if the blue box can be move and stop.</p>'
          +'</font>';
