var step = '<font style="font-size:85%">'
          +'<p>Test purpose: </p>'
          +'<ol>'
            +'<li>Check that <a href="https://crosswalk-project.org/jira/browse/XWALK-2231">XWALK-2231</a> is fixed.</li>'
            +'<li>Check if JavaScript to generate media streams for playback.</li>'
          +'</ol>'
          +'<p>Test step: </p>'
          +'<ol>'
            +'<li>Click player button to run the sample.</li>'
          +'</ol>'
          +'<p>Expected result: </p>'
          +'<p>The sample runs normally.</p>'
        +'</font>';
