var step = '<font style="font-size:85%">'
        + '<p>Test Purpose: </p>'
        + '<p>Verifies the device supports tizen vehicle information and vehicle data API.</p>'
        + '<p>Pre-condition: </p>'
        + '<p>Enable bluemonkey plugin following https://wiki.tizen.org/wiki/AMB_Bluemonkey_Plugin</p>'
        + '<p>Test Step: </p>'
        + '<p>'
          + '<ol>'
            + '<li>'
              + 'Click the "Get vehicle" button.'
            + '</li>'
          + '</ol>'
        + '</p>'
        + '<p>Expected Result: </p>'
        + '<p>Test passes if the detected direction reflects the actual vehicle information</p>'
      + '</font>'
