var step = '<font class="fontSize">'
           + '<p>Test Purpose:</p>'
           + '<p>Verifies the sessionStorage and localStorage work well.</p>'
           + '<p>Test Steps:</p>'
             + '<ol>'
               + '<li>Input text in "sessionStorage" and "localStorage" area, click button "Add Storage"</li>'
               + '<li>Input key which needs removed in "sessionStorage" or "localStorage" area, click button "Remove Storage"</li>'
             + '</ol>'
           + '<p>Expected Result:</p>'
             + '<ol>'
               + '<li>Stored data should be displayed in "Message" area</li>'
               + '<li>Left data should be displayed in "Message" area</li>'
             + '</ol>'
         + '</font>'
