var step = '<font class="fontSize">'
           + '<p>Test Purpose: </p>'
           + '<p>Verifies WebSocket send and recive message.</p>'
           + '<p>Test Pre-condition: </p>'
           + '<p>Start Websocket Server with listening port 8081.</p>'
           + '<p>Test Steps: </p>'
             + '<ol>'
               + '<li>Click the "Connect" button</li>'
               + '<li>When Websocket Server connected successfully, click the "Send" button</li>'
               + '<li>Click the "Disconnect" button</li>'
             + '</ol>'
           + '<p>Expected Result: </p>'
           + '<p>Test passes if WebSocket connect to Server and WebSocket recive whatever self send to server successfully.</p>'
         + '</font>'
