var step = '<font class="fontSize">'
           + '<p>Test Purpose: </p>'
           + '<p>Verifies WiFi Direct can discover and initiate connect to nearby WiFi Direct capable devices.</p>'
           + '<p>Test Steps: </p>'
             + '<ol>'
               + '<li>Device WiFi should be turned on and device should be WiFi Direct capable.</li>'
               + '<li>Click one of the available devices to connect</li>'
               + '<li>When connection is established, click "Disconnect"</li>'
             + '</ol>'
           + '<p>Expected Result: </p>'
           + '<p>Test passes if nearby WiFi Direct capable and available devices (means awaits connection) are listed and it is posible to invite some of them and connect.</p>'
         + '</font>'
