var step = '<font class="fontSize">'
            +'<p>Pre-condition:</p>'
            +'<ul>'
            +'<li>Connect to network</li>'
            +'<li>The plugin inappbrowser and network-information have been installed</li>'
            +'</ul>'
            +'<p>Purpose:</p>'
            +'<p>Verify the inappbrowser can work well</p>'
            +'<p>Test Steps:</p>'
            +'<ol>'
            +'<li>Click the button "Open remote PDF(target=Default)"</li>'
            +'<li>Click the button "Open local PDF(target=Default)"</li>'
            +'<li>Click the button "Open remote PDF(target=_self)"</li>'
            +'<li>Click the button "Open local PDF(target=_self)"</li>'
            +'<li>Click the button "Open Cookie Page"</li>'
            +'</ol>'
            +'<p>Expected Results:</p>'
            +'<ol>'
            +'<li>Open a document list</li>'
            +'<li>Open local PDF</li>'
            +'<li>Open a document list</li>'
            +'<li>Open local PDF</li>'
            +'<li>Get main page cookie</li>'
            +'</ol>'
          +'</font>';
