var step = '<font class="fontSize">'
           + '<p>Test Purpose: </p>'
           + '<p>Verifies the functionality of NFC works well.</p>'
           + '<p>Test Steps: </p>'
             + '<ol>'
               + '<li>Click "Turn OFF NFC".</li>'
               + '<li>Click "Turn ON NFC".</li>'
               + '<li>Click "Tap to Write", then tap NFC tag to the NFC adapter.</li>'
               + '<li>Click "Tap to Read", then tap NFC tag to the NFC adapter.</li>'
               + '<li>Click "Send URI NDEF to peer", then tap other NFC device to the NFC adapter.</li>'
              + '</ol>'
           + '<p>Expected Result: </p>'
             + '<ol>'
               + '<li>Print "Power off succeeded"</li>'
               + '<li>Print "Power on succeeded"</li>'
               + '<li>Print "Write nfc tag succeeded"</li>'
               + '<li>Print "Read nfc tag succeeded"</li>'
               + '<li>Print "Send URI NDEF succeeded"</li>'
             + '</ol>'
         + '</font>'
