var step = '<font style="font-size:85%">'
           + '<p>Test Purpose: </p>'
           + '<p>Verifies the device supports tizen SecureElement APi.</p>'
           + '<p>Test Step: </p>'
           + '<p>'
             + '<ol>'
               + '<li>'
                 + 'Click the "Get Readers Name" button.'
               + '</li>'
             + '</ol>'
           + '</p>'
           + '<p>Expected Result: </p>'
           + '<p>Test passes if show readers names, reader is ready or not and session is closed or not.</p>'
         + '</font>'
