var step = '<font class="fontSize">'
            +'<p>Test Steps:</p>'
            +'<ol>'
            +'<li>Follow the test scenario table to complete the tests</li>'
            +'<li>Install the test app and launch it, then input value and click "Set localStorage", "Set IndexDB" and "Set Web SQL Database"</li>'
            +'<li>Install the corresponding upgrade app(use "adb install -r *apk" to force install), then click "Get localStorage", "Get IndexDB" and "Get Web SQL Database"</li>'
            +'</ol>'
            +'<p>Expected Results:</p>'
            +'<ol>'
            +'<li>All tests can be upgrade successfully</li>'
            +'<li>Display "Save localStorage/IndexDB/Web SQL Database value successfully: " add input content in the box</li>'
            +'<li>Display "Get localStorage/IndexDB/Web SQL Database value: " add input content in the box</li>'
            +'</ol>'
          +'</font>';
