var step = '<font class="fontSize">'
            +'<p>Purpose:</p>'
            +'<p>Verify the Cordova StatusBar plugin can work when app in fullscreen mode</p>'
            +'<p>Expected Results:</p>'
            +'<ol>'
            +'<li>The app can be installed successfully</li>'
            +'<li>The app can launch successfully</li>'
            +'<li>The app can run successfully</li>'
            +'<li>The app show the StatusBar after click the "Status Bar Show" button</li>'
            +'<li>The app hide the StatusBar after click the "Status Bar Hide" button</li>'
            +'<li>The app can exit successfully</li>'
            +'</ol>'
          +'</font>';
