var step = '<font class="fontSize">'
            +'<p>Expected results</p>'
            +'<ol>'
            +'<li>Install app successfully, no error, no warning message</li>'
            +'<li>You will see a normal blue icon with text "Manifest PNG"</li>'
            +'<li>Display "Splash Screen Auto" with blue background after launch the app successfully</li>'
            +'<li>Display some descriptions about manifest configuration </li>'
            +'<li>Switch the screen normally</li>'
            +'<li>Display status bar</li>'
            +'</ol>'
            +'<p>This sample demonstrates manifest members "icons" and "xwalk_launch_screen"</p>'
            +'<ul>'
            +'<li>App configure values include: png format icons and custom ready_when</li>'
            +'<li>Xwalk_launch_screen members'
            +'<ul>'
            +'<li>Ready_when: The application readiness state at which to hide the launch screen</li>'
            +'<ul>'
            +'<li>Custom:'
            +'<ul>'
            +'<li>The first visually non-empty paint has occurred</li>'
            +'<li>The window.screen.show() method was called</li>'
            +'</ul>'
            +'</li>'
            +'</ul>'
            +'</ul>'
            +'</li>'
            +'</ul>'
          +'</font>';
