var step = '<font style="font-size:85%">'
          +'<p>Test purpose: </p>'
          +'<ol>'
            +'<li>Check that <a href="https://crosswalk-project.org/jira/browse/XWALK-2578">XWALK-2578</a> is fixed.</li>'
            +'<li>Check programmatic switching of applications feature whether or not supported.</li>'
          +'</ol>'
          +'<p>Test step: </p>'
          +'<ol>'
            +'<li>Click "TestResume1 Install" to install TestResume1.</li>'
            +'<li>Click "TestResume2 Install" to install TestResume2.</li>'
            +'<li>Click "Launch" to launch TestResume1 application.</li>'
            +'<li>Click TestResume1 application checkbox to switch TestResume2.</li>'
            +'<li>Click TestResume2 application checkbox to switch TestResume1.</li>'
            +'<li>Click "TestResume UnInstall" to uninstall TestResume.</li>'
          +'</ol>'
          +'<p>Expected result: </p>'
          +'<p>TestResume1 and TestResume2 applications switch each other successfully.</p>'
        +'</font>';
