var step = '<font class="fontSize">'
           + '<p>Test Purpose: </p>'
           + '<p>Verifies the device supports notification interface.</p>'
           + '<p>Test Step: </p>'
           + '<p>'
             + '<ol>'
               + '<li>'
                 + 'Click the "Show Notification" button.'
               + '</li>'
               + '<li>'
                 + 'Click the "Close Notification" button.'
               + '</li>'
             + '</ol>'
           + '</p>'
           + '<p>Expected Result: </p>'
           + '<p>Test passes if show a notification after step 1, and then this notification close after step 2.</p>'
         + '</font>'
