var step = '<font style="font-size:85%">'
            +'<p>Test Purpose: </p>'
            +'<p>Verifies the attributes of CSS3 Media Queries show currectly.</p>'
            +'<p>Test Steps: </p>'
            +'<ol>'
              +'<li>Click the \'Set Color\'</li>'
              +'<li>When the color of content is changed, click the "Area Width" to check out the width of current viewing area</li>'
            +'</ol>'
            +'<p>Expected Result: </p>'
            +'<p>Test passes if the content display with right color when change the size of viewing area.</p>'
          +'</font>';
