var step = '<font class="fontSize">'
            +'<p>Purpose:</p>'
            +'<p>Validate the localStorage functionality is available</p>'
            +'<p>Expected Result:</p>'
            +'<ol>'
            +'<li>The webapp install successfully and launch successfully.</li>'
            +'<li>The textarea will output "Save localStorage value successfully:..."</li>'
            +'<li>The textarea will output "Get localStorage value:..."</li>'
            +'</ol>'
          +'</font>';
