var step = '<font class="fontSize">'
            +'<p>Purpose:</p>'
            +'<p>Verifies that Packaging Tool support the "x86" arch, "app-url", "mode=shared", "verbose" and "keep-screen-on" options</p>'
            +'<p>Expected Result:</p>'
            +'<ol>'
            +'<li>Apk with "x86" arch and shared mode could be created successfully</li>'
            +'<li>Apk with "arm" arch and shared mode could be created successfully</li>'
            +'<li>More detailed messages can be got in the second packaging process</li>'
            +'<li>Web App could be installed successfully</li>'
            +'<li>Version of the two web apps are both 1.0.0</li>'
            +'<li>The screen keep on for more than 15 seconds</li>'
            +'<li>Web App could be launched successfully, the home page display intel and keep screen on status more than 15 seconds</li>'
            +'</ol>'
          +'</font>';
