var step = '<font class="fontSize">'
            +'<p>Pre-condition</p>'
            +'<ol>'
            +'<li>There is at least 1 image in the device</li>'
            +'<li>Connect a device to host by usb</li>'
            +'</ol>'
            +'<p>Test Steps</p>'
            +'<ol>'
            +'<li>Run command in terminal:<br/>$ adb shell content query --uri content://media/external/images/media</li>'
            +'<li>Set the "_id" value to "Image Id" textarea</li>'
            +'<li>Click the link "Open Image"</li>'
            +'</ol>'
            +'<p>Expected Results</p>'
            +'<ol>'
            +'<li>List all image id successfully</li>'
            +'<li>Input "_id" value to "Image Id" textarea successfully</li>'
            +'<li>Display selected image successfully</li>'
            +'</ol>'
          +'</font>';
