var step = '<font class="fontSize">'
            + '<p>Test Purpose: </p>'
            + '<p>Verify to query the product details and buy the in-app product successfully.</p>'
            + '<p>Expected Result: </p>'
            + '<p>It will firstly notify that "You are now logining in the Xiaomi Game Center"</p>'
            + '<p>Querying the product details and buying the in-app product successfully.</p>'
            + '<p>There is a purchase record in your Xiaomi Wallet or Alipay app.</p>'
            + '<p>Notice: </p>'
            + '<p>It is acceptable for some other features failed and noticed as "NotSupportError" as Xiaomi App Store does not support them.</p>'
          +'</font>';
