var step = '<font class="fontSize">'
           + '<p>Test Purpose: </p>'
           + '<p>Verifies the functionalities of viewport. Tests the functionality of setting device height and width, scale, enabling or disabling user scalable to allow or disallow zoom in/out screen, sliding the screen by figure.</p>'
           + '<p>Expected Result: </p>'
           + '<p>Test passes if all the check points work well.</p>'
         + '</font>'
