var step = '<font style="font-size:85%">'
             +'<p>Test Steps:</p>'
             +'<ol>'
             +'<li>Click "Unoverlapped" button N times(N>2)</li>'
             +'<li>Click the popup advertising, select "visit website"</li>'
             +'<li>Click blank area</li>'
             +'<li>Click "Overlapped" button N times(N>2)</li>'
             +'<li>Repeat step2 and step3</li>'
             +'<li>Click "Interstitial"</li>'
             +'</ol>'
             +'<p>Expected Results:</p>'
             +'<ol>'
             +'<li>Create N unoverlapped advertising and display "Show un-overlop advertising" and "Un-overlop advertising loaded" in the textarea</li>'
             +'<li>Display "Fired onopen event" in the textarea</li>'
             +'<li>Display "Fired onclose event" in the textarea</li>'
             +'<li>Create one advertizing banner and refreshed with new ad, but display N times with "Show overlop advertising" and "Overlop advertising loaded" in the textarea</li>'
             +'<li>The situation same as result2 and result3</li>'
             +'<li>Popup a advertising with fullscreen and display "Show interstitial advertising" and "Interstitial advertising loaded" in the textarea</li>'
             +'</ol>'
           +'</font>';
