var step = '<font class="fontSize">'
           + '<p>Test Purpose: </p>'
           + '<p>Verifies the SIMD is supported and valid.</p>'
           + '<p>Test Step: </p>'
           + '<p>'
             + '<ol>'
               + '<li>'
                 + 'Press start button and remeber the FPS num.'
               + '</li>'
               + '<li>'
                 + 'Then press the use simd button and rember the FPS num again.'
               + '</li>'
             + '</ol>'
           + '</p>'
           + '<p>Expected Result: </p>'
           + '<p>Test passes if FPS num with simd is larger than without simd.</p>'
         + '</font>'
