var step = '<font class="fontSize">'
           + '<p>Test Purpose: </p>'
           + '<p>Verifies the Screen Orientation is supported, and can be changed.</p>'
           + '<p>Test Steps: </p>'
           + '  <ol>'
           + '    <li>Click the "FullSreen"</li>'
           + '    <li>Click the Lock button</li>'
           + '    <li>Click the "Cancel FullScreen" button</li>'
           + '  </ol>'
           + '<p>Expected Result: </p>'
           + '  <ol>'
           + '    <li>Switch to FullScreen mode</li>'
           + '    <li>The Screen Orientation can be locked.</li>'
           + '    <li>Quit FullScreen mode, Screen Orientation change to unlock state.</li>'
           + '  </ol>'
           + '</font>'
