var step = '<font class="fontSize">'
            +'<p>Test Note: </p>'
            +'<p>Verifies the functionality of CSP worked well.</p>'
            +'<p>Test Pre-condition: </p>'
            +'<p>Start Tinyweb server.</p>'
            +'<p>Test Purpose: </p>'
            +'<p>Verifies the functionality of CSP worked well.</p>'
            +'<p>Expected Result: </p>'
            +'<p>Test passes if all sub-tests pass.</p>'
          +'</font>';
