var step = '<font class="fontSize">'
            +'<p>Expected results</p>'
            +'<ol>'
            +'<li>Install app successfully, no error, no warning message</li>'
            +'<li>You will see a normal purple icon with text "Manifest JPG" and the version value as "1.0.0.0.120150101"</li>'
            +'<li>Display "Splash Screen Landscape" with purple background and landscape screen in Splash Screen after launch the app successfully</li>'
            +'<li>Display some descriptions about manifest configuration with landscape screen</li>'
            +'<li>Display status bar</li>'
            +'</ol>'
            +'<p>This sample demonstrates manifest members "icons", "xwalk_version", "orientation", "display", "xwalk_launch_screen"</p>'
            +'<ul>'
            +'<li>App configure values include: jpg format icons, five digits version, landscape orientation, minimal-ui display, first-paint ready_when and landscape</li>'
            +"<li>Minimal-ui: This mode is similar to fullscreen, but provides the end-user with some means to access a minimal set of UI elements for controlling navigation (i.e., back, forward, reload, and perhaps some way of viewing the document's address)</li>"
            +'<li>Xwalk_launch_screen members'
            +'<ul>'
            +'<li>Ready_when: The application readiness state at which to hide the launch screen</li>'
            +'<ul>'
            +'<li>First-paint:'
            +'<ul>'
            +'<li>The first visually non-empty paint has occurred</li>'
            +'</ul>'
            +'</li>'
            +'</ul>'
            +'<li>Landscape: The launch screen to use for landscape mode</li>'
            +'</ul>'
            +'</li>'
            +'</ul>'
          +'</font>';
