var step = '<p>Purpose:</p>'
            +'<p>Verify that the shared mode app using --xwalk-apk-url parameter can download crosswalk library apk after launch it</p>'
            +'<p>Expected Results:</p>'
            +'<ol>'
            +'<li>Create test suite(SharedModeLibraryDownload) successfully</li>'
            +'<li>Build the apk successfully</li>'
            +'<li>The app can be installed successfully</li>'
            +'<li>The app can launch successfully</li>'
            +'<li>Display message "Please get Crosswalk Runtime Library"</li>'
            +'<li>Start to download the XWalkRuntimeLib.apk</li>'
            +'<li>Display "App installed"</li>'
            +'<li>The app can run successfully</li>'
            +'<li>The app can exit successfully</li>'
            +'</ol>';
