var step = '<p>Purpose:</p>'
            +'<p>Verify that the shared mode app using --xwalk-apk-url parameter can download crosswalk library apk after launch it</p>'
            +'<p>Expected Results:</p>'
            +'<ol>'
            +'<li>The command run successfully, no error</li>'
            +'<li>The console display "Build Package Successfully" and "Package Name Consistent"</li>'
            +'<li>The app is running and display message "Please get Crosswalk Runtime Library"</li>'
            +'<li>Start to download the XWalkRuntimeLib.apk</li>'
            +'<li>Display "App installed"</li>'
            +'<li>The app can run successfully</li>'
            +'<li>The app can exit successfully</li>'
            +'<li>The app can be uninstalled successfully</li>'
            +'</ol>';
