var step = '<font class="fontSize">'
            +'<p>Purpose:</p>'
            +'  <p>Verifies that the web media player work well with screen rotation.</p>'
            +'<p>Pre-condition:</p>'
            +'<ul>'
            +'  <li>Conntect to network.</li>'
            +'</ul>'
            +'<p>Expected Result:</p>'
            +'<ol>'
            +'  <li>The apk is installed successfully</li>'
            +'  <li>The app is launched and Youku.com is loaded</li>'
            +'  <li>The video is playing successfully</li>'
            +'  <li>The screen rotate and the video is playing well</li>'
            +'  <li>The video is playing in full screen mode</li>'
            +'  <li>The screen rotate and the video is playing well in full screen mode</li>'
            +'</ol>'
          +'</font>';
