var step = '<font class="fontSize">'
            +'<p>Test Purpose: </p>'
            +'<p>Verifies js and css animation will suspend when application goes invisible.</p>'
            +'<p>Test Step: </p>'
            +'<ol>'
            +'<li>Launch another exist App(Webapp or Native app) to let this tct-behavior-test lost focus, what is, let it to background and not in top screen.</li>'
            +'<li>Resume tct-behavior-test to top screen, e.g. click tct-behavior-test window, or start task switcher and select tct-behavior-tests again.</li>'
            +'</ol>'
            +'<p>Expected Result: </p>'
            +'<ul>'
            +'<li>The "JS time" is different from the "Difference time".</li>'
            +'<li>The "Animation time" is different from the "Difference time".</li>'
            +'</ul>'
          +'</font>';
