var step = '<font style="font-size:85%">'
            +'<p>Test Purpose: </p>'
            +'<p>Check if add and remove bookmark successfully</p>'
            +'<p>Test Steps: </p>'
            +'<ol>'
              +'<li>Click the \'Page A\'</li>'
              +'<li>Click the \'Remove Bookmark\'</li>'
              +'<li>Click the \'Page B\'</li>'
              +'<li>Click the \'Add Bookmark\'</li>'
              +'<li>Click the \'Remove Bookmark\'</li>'
            +'</ol>'
            +'<p>Expected Result: </p>'
            +'<p>Test passes if the bookmark can be added and removed successfully</p>'
          +'</font>';
