var step = '<font class="fontSize">'
            +'<p>Purpose:</p>'
            +'<p>Verify the Cordova app remotedebugging features</p>'
            +'<p>Expected Results:</p>'
            +'<ol>'
            +'<li>The "remotedebugging" app could be installed successfully</li>'
            +'<li>The icon display correctly and the same as icon in Apps</li>'
            +'<li>The "remotedebugging" app could launche and run successfully</li>'
            +'<li>The "remotedebugging" app will be shown in the inspection page and the web app name correctly.</li>'
            +'<li>The "remotedebugging" app source code will shown</li>'
            +'<li>The source code could be changed</li>'
            +'<li>The change will take effect</li>'
            +'<li>The Debug information on the right side, such as "Breakpoints", "DOM Breakpoints"</li>'
            +'<li>The Breakpoint could be added successfully</li>'
            +'<li>The console of the debug page is shown</li>'
            +'<li>The "remotedebugging" app works well, there is no crash after execute history.replaceState method</li>'
            +'<li>"chrome-extension://android_asset/anything" is shown on the console after execute "location.href"</li>'
            +'</ol>'
          +'</font>';
