var step = '<font class="fontSize">'
            +'<p>Expected results</p>'
            +'<ol>'
            +'<li>Install app successfully, no error, no warning message</li>'
            +'<li>You will see a normal navy icon with text "Manifest WebP"</li>'
            +'<li>Display "Splash Screen Auto" with navy background after launch the app successfully</li>'
            +'<li>Display some descriptions about manifest configuration with landscape screen</li>'
            +'<li>Switch the screen normally</li>'
            +'<li>Display status bar</li>'
            +'</ol>'
            +'<p>This sample demonstrates manifest members "icons"</p>'
            +'<p>App configure values include: webp format icons and defult system setting<p>'
          +'</font>';
