var step = '<font class="fontSize">'
            +'<p>Purpose:</p>'
            +'<p>Verify the Cordova package can build, install and launch successfully</p>'
            +'<p>Expected Results:</p>'
            +'<ol>'
            +'<li>There are arm and x86 apk files generated in hello/build/outputs/apk directory</li>'
            +'<li>The app can be installed successfully</li>'
            +'<li>The app can launch successfully</li>'
            +'<li>The app can run successfully</li>'
            +'<li>The app can exit successfully</li>'
            +'</ol>'
          +'</font>';
