var step = '<font class="fontSize">'
            +'<p>Pre-condition: </p>'
            +'<ol>'
            +'<li>A network connection capable of accessing the internet MUST be established.</li>'
            +'</ol>'
            +'<p>Purpose:</p>'
            +'<p>Verifies the wrt command line</p>'
            +'<p>Expected Result:</p>'
            +'<ol>'
            +'<li>List Available runtime features flags:<br>--disable-sysapps<br>--disable-raw-sockets<br>--disable-device-capabilities<br>--disable-storage<br>--enable-dialog </li>'
            +'<li>Webapp launched with fullscreen window successfully</li>'
            +'<li>Access baidu website successfully</li>'
            +'</ol>'
          +'</font>';
