var step = '<font class="fontSize">'
           + '<p>Test Purpose: </p>'
           + '<p>Verifies WebCrypto APIs support generate key, sign data, verify data.</p>'
           + '<p>Test Steps: </p>'
             + '<ol>'
               + '<li>Click the "Generate Key"</li>'
               + '<li>Click the "Sign Data"</li>'
               + '<li>Click the "Verify Data"</li>'
             + '</ol>'
           + '<p>Expected Result: </p>'
           + '<p>Test passes if correct data about key, signature displayed</p>'
         + '</font>'
