var step = '<font class="fontSize">'
        + '<p>Test Purpose: </p>'
        + '<p>Verifies the device supports filter images by width and height.</p>'
        + '<p>Test Step: </p>'
        + '<p>'
          + '<ol>'
            + '<li>'
              + 'Input filter images width in first input box.'
            + '</li>'
            + '<li>'
              + 'Input filter images height in second input box.'
            + '</li>'
            + '<li>'
              + 'Select the filter type.'
            + '</li>'
            + '<li>'
              + 'Click the "Filter" button.'
            + '</li>'
          + '</ol>'
        + '</p>'
        + '<p>Expected Result: </p>'
        + '<p>Test passes if display images info by input width and height.</p>'
      + '</font>'
