var step = '<font class="fontSize">'
           + '<p>Test Purpose: </p>'
           + '<p>Verifies the Typed Array can be created, set and got</p>'
           + '<p>Test Steps: </p>'
             + '<ol>'
               + '<li>Click the "Set & Get Value" button.</li>'
             + '</ol>'
           + '<p>Expected Result: </p>'
           + '<p>Test passes if the array is initialized with 0 and can be filled to 1.</p>'
         + '</font>'
