var step = '<font class="fontSize">'
            +'<p>Purpose:</p>'
            +'<p>Verifies that CordovaWebView can use canGoBack() method successfully</p>'
            +'<p>Test Steps:</p>'
            +'<li>Check the value of "CordovaWebView.canGoBack()" on the page</li>'
            +'<p>Expected Result:</p>'
            +'<ol>'
            +'<li>The value of "CordovaWebView.canGoBack()" is true</li>'
            +'</ol>'
          +'</font>';
