var step = '<font class="fontSize">'
            +'<p>Purpose:</p>'
            +'<p>Verifies that the WebApp common operation, fullscreen and version update</p>'
            +'<p>Expected Result:</p>'
            +'<ol>'
            +'<li>Webapp is launch and show fullscreen mode successfully</li>'
            +'<li>The sample one WebApp version is: 1.1.1.1 </li>'
            +'<li>The sample one WebApp version is updated to: 1.1.1.2 </li>'
            +'<li>The WebApp is launched successfully</li>'
            +'<li>Web app is able to be uninstalled successfully</li>'
            +'</ol>'
          +'</font>';
