var step = '<font style="font-size:85%">'
           + '<p>Check if PushClient gets messages from the push server</p>'
           + '<p>A network connection capable of accessing the Internet MUST be established </p><br>'
           + '<p>1. Install and launch PushClient(TestPush) Application</p>'
           + '<p>   (Make sure the device is online and the applications shows registration success popup.)'
           + '<p>2. Press Hide in the PushClient</p>'
           + '<p>3. Back to this page and fill in a push message and click Push button</p>'
           + '<p>4. Check PushClient becomes foreground showing PASS text</p>'
           + '<p>5. Exit PushClient</p>'
           + '<p>6. Back to this page and fill in another message and click Push button</p>'
           + '<p>7. Check a notification pops up and PushClient launchs with PASS text when the notification is clicked</p>'
         + '</font>'
