var step = '<font class="fontSize">'
           + '<p>Test Purpose: </p>'
           + '<p>Verifies use time interface can get and change time information.</p>'
           + '<p>Test Steps: </p>'
             + '<ol>'
               + '<li>Run the application, check if current time information can be shown vaild.</li>'
               + '<li>Input number and press "submit", check if the time information is changed.</li>'
              + '</ol>'
           + '<p>Expected Result: </p>'
           + '<p>Test passes if time information can be shown normally and changed success.</p>'
         + '</font>'
