var step = '<font class="fontSize">'
            +'<p>Test Purpose: </p>'
            +'<p>Verifies the interfaces and methods of calendar is supported and valid.</p>'
            +'<p>Test Steps: </p>'
            +'<ol>'
              +'<li>when open the page,if the page show 'undefined' means the tizen.calendar is undefined and you can not do the following steps.</li>'
              +'<li>Click the \'Add\' button, check if the calendar can add an item synchronously.</li>'
              +'<li>Click the \'addBatch\' button, check if the calendar can add an array of items asynchronously.</li>'
              +'<li>Click the \'Update\' button, check if an existing item in the calendar can be updated.</li>'
              +'<li>Click the \'updateBatch\' button, check if an array of existing items in the calendar can be updated.</li>'
              +'<li>Click the \'Remove\' button, check if an item can be removed from the calendar that corresponds to the specified identifier.</li>'
              +'<li>Click the \'removeBatch\' button, check if several items can be removed from the calendar asynchronously depending on the specified identifiers</li>'
              +'<li>Click the \'Find\' button, check if an array of CalendarItem objects for items stored in the calendar can be found.</li>'
              +'<li>Click the \'Clone\' button, check if the CalendarItem object can be cloned, detached from any calendar.</li>'
            +'</ol>'
            +'<p>Expected Result: </p>'
            +'<p>Test passes if interfaces and methods of calendar is supported and valid normally.</p>'
          +'</font>';
