var step = '<font class="fontSize">'
            +'<p>Purpose:</p>'
            +'<p>Validate the indexDB functionality is available and it is exist when relaunch the app or relaunch the app after reboot the system</p>'
            +'<p>Expected Result:</p>'
            +'<ol>'
            +'<li>The webapp install successfully and launch successfully.</li>'
            +'<li>The textarea will output "Save indexDB value successfully:'input message'"</li>'
            +'<li>The textarea will output "Get indexDB value:'input message'" </li>'
            +'</ol>'
          +'</font>';
