var step = '<font class="fontSize">'
            +'<p>Purpose:</p>'
            +'<p>Confirm the widget application is encrypted or not.</p>'
            +'<p>Expected Result:</p>'
            +'<ol>'
            +'<li>Folder can be created successfully.</li>'
            +'<li>The webapp can be installed successfully.</li>'
            +'<li>The webapp file can not be listed successfully.</li>'
            +'<li>The index.html is showing normally.</li>'
            +'<li>Webapp can be uninstalled successfully.</li>'
            +'</ol>'
          +'</font>';
