var step = '<font class="fontSize">'
           + '<p>Test Purpose: </p>'
           + '<p>Verifies go back or forward the specifiednumber of steps in the session history.</p>'
           + '<p>Test Steps: </p>'
             + '<p>The page will add 10 session history state from 1 - 10, tap "back" or "forward" button will back or forward current history state'
             + '</p>'
           + '<p>Expected Result: </p>'
           + '<p>Test passes if go back or forward page will change window.history.state well.</p>'
         + '</font>'
