var step = '<font class="fontSize">'
            +'<p>Purpose:</p>'
            +'<p>Verifies that Packaging Tool support the "app-version", "app-local-path", "name", "package", "description", "fullscreen", default "icon", "mode=embedded", "orientation=landscape", "target-dir", "project-dir" and default "arch" options</p>'
            +'<p>Expected Result:</p>'
            +'<ol>'
            +'<li>Two apks is created in the target dir successfully</li>'
            +'<li>The version of the web app is 1.0.0</li>'
            +'<li>An app folder is generated successfully in packer tool</li>'
            +'<li>Variable path for description can be found</li>'
            +'<li>Description of the web app is "YourApplicationDescription"</li>'
            +'<li>Web App could be installed successfully</li>'
            +'<li>Web App could be launched with fullscreen and screen orientation is landscape</li>'
            +'</ol>'
          +'</font>';
