var step = '<font class="fontSize">'
            +'<p>Purpose:</p>'
            +'<p>Verifies that enable cookie add, remove and update</p>'
            +'<p>Pre-condition:</p>'
            +'<ul>'
            +'<li>Connect to network</li>'
            +'</ul>'
            +'<p>Test steps:</p>'
            +'<ol>'
            +'<li>Input new Cookie name & value and Click "Set Test Cookie"</li>'
            +'<li>Continue to add new cookies for 3 times</li>'
            +'<li>Select one exist cookies name, copy to "Cookie name" input box, and changes the value its value in "Cookie value" input box, then click "Set Test Cookie" to update it</li>'
            +'<li>Click "Remove Cookie" button</li>'
            +'</ol>'
            +'<p>Expected Result:</p>'
            +'<ol>'
            +'<li>New cookie is added and showing correctly</li>'
            +'<li>All cookies are added and showing correctly</li>'
            +'<li>After Set Test Cookie the Cookies value can be updated successfully</li>'
            +'<li>Cookies can be removed successfully</li>'
            +'</ol>'
          +'</font>';
