var step = '<p>Purpose:</p>'
            +'<p>Verifies "basicapp" app can run successfully</p>'
            +'<p>Expected Result:</p>'
            +'<ol>'
            +'<li>Find the "basicapp" app successfully</li>'
            +'<li>Launch the "basicapp" app successfully</li>'
            +'<li>You can see "This is a Crosswalk Sample Application" on the device</li>'
            +'<li>Unistall the "basicapp" app successfully when the app running</li>'
            +'<li>Stop the "basicapp" app successfully</li>'
            +'<li>Unistall the "basicapp" app successfully</li>'
            +'</ol>';
