var step = '<font class="fontSize">'
           + '<p>Test Purpose: </p>'
           + '<p>Verifies the device supports show presentation by clicking the "Request Show Presentation" button.</p>'
           + '<p>Precondition: </p>'
           + '<p>Turn on "Simulate Secondary Display" by "Setting" app.</p>'
           + '<p>Test Step: </p>'
           + '<p>'
             + '<ol>'
               + '<li>'
                 + 'Check the staus value.'
               + '</li>'
               + '<li>'
                 + 'Click the "START" button, check the status value.'
               + '</li>'
               + '<li>'
                 + 'Click the "TERMINATE" button, check the status value.'
               + '</li>'
             + '</ol>'
           + '</p>'
           + '<p>Expected Result: </p>'
           + '<p>Test passes: </p>'
           + '<p>'
             + '<ol>'
               + '<li>'
                 + 'The status are: Display availability: available, '
                 + '                Session state: no session, '
                 + '                Presentation ID: none.'
               + '</li>'
               + '<li>'
                 + 'The status are: Display availability: available, '
                 + '                Session state: connected, '
                 + '                Presentation ID is not none.'
               + '</li>'
               + '<li>'
                 + 'The values are: Display availability: available, '
                 + '                Session state: closed '
                 + '                Presentation ID: none.'
               + '</li>'
             + '</ol>'
           + '</p>'
         + '</font>'
