var step = '<font style="font-size:85%">'
            +'<p>Test Purpose: </p>'
            +'<p>Verifies the telephony is supported and valid</p>'
            +'<p>Test Steps: </p>'
            +'<ol>'
              +'<li>Click the \'Add Service Listeners\'</li>'
              +'<li>Click the \'Add Call Listeners\'</li>'
              +'<li>Click the \'Get Services\'</li>'
              +'<li>Click the \'Get Default Service\'</li>'
              +'<li>Click the \'Get Active Call\'</li>'
              +'<li>Click the \'Get All Calls\'</li>'
              +'<li>Click the \'Dial\'</li>'
              +'<li>Click the \'Create Conference\'</li>'
              +'<li>Click the \'Get Conference Participants\'</li>'
              +'<li>Click the \'Split\'</li>'
              +'<li>Click the \'Disconnect Active Call\'</li>'
              +'<li>Click the \'Disconnect All Calls\'</li>'
              +'<li>Click the \'Hold Active Call\'</li>'
              +'<li>Click the \'Resume Held Call\'</li>'
              +'<li>Click the \'Accept Incoming/Waiting Call\'</li>'
              +'<li>Click the \'Deflect Incoming/Waiting Call\'</li>'
              +'<li>Click the \'Transfer Incoming/Waiting call\'</li>'
              +'<li>Click the \'Get Emergency Numbers\'</li>'
              +'<li>Click the \'Remove Call Listeners\'</li>'
              +'<li>Click the \'Remove Service Listeners\'</li>'
              +'<li>Click the \'Send Tones\'</li>'
              +'<li>Click the \'Start Tone\'</li>'
              +'<li>Click the \'End Tone\'</li>'
              +'<li>Click the \'Show\'</li>'
              +'<li>Click the \'Set As Default\'</li>'
              +'<li>Click the \'Enable Service\'</li>'
              +'<li>Click the \'Disable Service\'</li>'
            +'</ol>'
            +'<p>Expected Result: </p>'
            +'<p>Test passes if get telephony services and operate telephony successfully</p>'
          +'</font>';
